parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/AbstractNamespacedMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ApplyMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/handler/ResourceEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/util/KubernetesResourceUtil.java, plugin/src/test/java/io/fabric8/maven/plugin/util/KubernetesResourceUtilTest.java
fixes #29 to add a fabric8:apply goal
=> fixes #29 to add a fabric8:apply goal

parent/pom.xml
fix exception in fabric8:apply by upgrading k8-client
=> fix exception in fabric8:apply by upgrading k8-client

plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultServiceEnricher.java
fixes up defaulting of the service name / metadata / ports if the user supplies a partial service
=> fixes up defaulting of the service name / metadata / ports if the user supplies a partial service

core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java, core/src/main/java/io/fabric8/maven/core/handler/PodTemplateHandler.java, core/src/main/java/io/fabric8/maven/core/handler/ReplicaSetHandler.java, core/src/main/java/io/fabric8/maven/core/handler/ReplicationControllerHandler.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java, core/src/test/java/io/fabric8/maven/core/util/PluginServiceFactoryTest.java, customizer/api/src/main/java/io/fabric8/maven/customizer/api/BaseCustomizer.java, customizer/spring-boot/src/main/java/io/fabric8/maven/customizer/spring/boot/SpringBootCustomizer.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/icon/src/main/java/io/fabric8/maven/enricher/icon/IconEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/AbstractFabric8Mojo.java, plugin/src/main/java/io/fabric8/maven/plugin/DeployMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultImageEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultNameEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultServiceEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/ProjectInfoEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java, sample/spring-boot/src/main/java/io/fabric8/maven/sample/spring/boot/HelloController.java
Need to find out where IDEA does this stupid auto import thing for static methods, which is *always* wrong.
=> Fixed imports

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
upgrade to latest fabric8 version which has ingress support
=> upgrade to latest fabric8 version which has ingress support

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
upgraded the kubernetes client
=> upgraded the kubernetes client

parent/pom.xml
The previous fix was overridden.
=> fixed javadoclint

sample/cdi-camel/pom.xml, sample/peng/pom.xml, sample/spring-boot/pom.xml
update versions of samples to use the latest build
=> update versions of samples to use the latest build

parent/pom.xml
=> upgrade fabric8

core/src/main/java/io/fabric8/maven/core/util/MavenUtil.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java, enricher/icon/src/main/java/io/fabric8/maven/enricher/icon/IconEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
fixes #4 so we auto-detect funktion, spring-boot, wildfly swarm, camel et al
=> fixes #4 so we auto-detect funktion, spring-boot, wildfly swarm, camel et al

plugin/src/main/java/io/fabric8/maven/plugin/AbstractFabric8Mojo.java, plugin/src/main/java/io/fabric8/maven/plugin/DeployMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
fixes #81 so we generate an openshift specific yaml file for openshift specific resources
=> fixes #81 so we generate an openshift specific yaml file for openshift specific resources

core/src/main/java/io/fabric8/maven/core/handler/DeploymentHandler.java, core/src/main/java/io/fabric8/maven/core/handler/HandlerHub.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultReplicaSetEnricher.java
fixes #46 so that we default to Deployment now; though you can disable it and it'll use RS; which you can disable too if need be
=> fixes #46 so that we default to Deployment now; though you can disable it and it'll use RS; which you can disable too if need be

parent/pom.xml
=> updated fabric8 version

plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultServiceEnricher.java
=> avoid possible NPE

core/src/main/java/io/fabric8/maven/core/util/MavenProperties.java, customizer/spring-boot/src/main/java/io/fabric8/maven/customizer/spring/boot/SpringBootCustomizer.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
lets expose the docker user, name and label as maven properties so we can refer to them inside custom <build> configurations
=> lets expose the docker user, name and label as maven properties so we can refer to them inside custom <build> configurations

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/main/java/io/fabric8/maven/core/util/ResourceClassifier.java, plugin/src/main/java/io/fabric8/maven/plugin/DeployMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
Now all generated resource files are stored within META-INF/fabric8
* Two file "kubernetes.yml" and "openshift.yml"
* Two directories "kubernetes" and "openshift" holding the individual resource items.
=> Refactored location of resource files

core/src/main/java/io/fabric8/maven/core/util/Configs.java, customizer/api/src/main/java/io/fabric8/maven/customizer/api/BaseCustomizer.java, customizer/api/src/main/java/io/fabric8/maven/customizer/api/CustomizerConfiguration.java, customizer/spring-boot/src/main/java/io/fabric8/maven/customizer/spring/boot/SpringBootCustomizer.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherConfiguration.java, enricher/api/src/main/test/io/fabric8/maven/enricher/api/EnricherConfigurationTest.java, enricher/icon/src/main/java/io/fabric8/maven/enricher/icon/IconEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultImageEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultNameEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultReplicaSetEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultServiceEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/ProjectInfoEnricher.java
Make it look a bit smarter. Also moved enricher name intitialization to the super constructor.
=> Refactor config handling again.

core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java, core/src/main/java/io/fabric8/maven/core/util/MavenUtil.java, core/src/main/java/io/fabric8/maven/core/util/SpringBootProperties.java
added liveness and readiness check generation for spring boot if the actuator is enabled
=> added liveness and readiness check generation for spring boot if the actuator is enabled

core/src/main/java/io/fabric8/maven/core/util/DockerUtil.java, customizer/spring-boot/src/main/java/io/fabric8/maven/customizer/spring/boot/SpringBootCustomizer.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/ProjectInfoEnricher.java
fixes #101 to use the actual docker label if its different from project.version
=> fixes #101 to use the actual docker label if its different from project.version

customizer/spring-boot/src/main/java/io/fabric8/maven/customizer/spring/boot/SpringBootCustomizer.java
lets let the alias be configured for the spring boot customizer
=> lets let the alias be configured for the spring boot customizer

core/src/main/java/io/fabric8/maven/core/config/ResourceConfiguration.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/Kinds.java, enricher/icon/src/main/java/io/fabric8/maven/enricher/icon/IconEnricher.java, enricher/icon/src/main/java/io/fabric8/maven/enricher/links/DocLinkEnricher.java, enricher/icon/src/main/java/io/fabric8/maven/enricher/links/GrafanaLinkEnricher.java, enricher/icon/src/main/resources/META-INF/fabric8-enricher-default
fixes #112 to link to the site URL for the mvn pom based on the current version
=> fixes #112 to link to the site URL for the mvn pom based on the current version

parent/pom.xml
upgrade docker-maven-plugin version
=> upgrade docker-maven-plugin version

core/src/main/java/io/fabric8/maven/core/util/MapUtil.java, enricher/icon/src/main/java/io/fabric8/maven/enricher/template/TemplateAnnotationEnricher.java, enricher/icon/src/main/resources/META-INF/fabric8-enricher-default
=> fixes #116

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, parent/pom.xml
upgrade fabric8 and fixed failing test
=> upgrade fabric8 and fixed failing test

plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultImageEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultNameEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultReplicaSetEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultServiceEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/MetadataEnricherVisitor.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java
fix visitor stuff for latest fabric8 / kubernetes-client
=> fix visitor stuff for latest fabric8 / kubernetes-client

plugin/src/main/java/io/fabric8/maven/plugin/docker/WatchMojo.java
first spike at a a fabric8:watch mojo. Needs some work mind ;)
=> first spike at a a fabric8:watch mojo. Needs some work mind ;)

customizer/java-app/pom.xml, customizer/java-app/src/main/java/io/fabric8/maven/customizer/javaapp/EnvironmentVariables.java, customizer/java-app/src/main/java/io/fabric8/maven/customizer/javaapp/JavaAppCustomizer.java, customizer/java-app/src/main/resources/META-INF/fabric8-customizer-default, customizer/java-app/src/main/resources/assemblies/java-app.xml, parent/pom.xml, plugin/pom.xml
first spike of a java-app customizer fixes #125
=> first spike of a java-app customizer fixes #125

release.groovy
lets try auto-update fabric8 + docker-maven-plugin versions as we release
=> lets try auto-update fabric8 + docker-maven-plugin versions as we release

parent/pom.xml
=> updated fabric8

release.groovy
add downstream dependencies to update eagerly
=> add downstream dependencies to update eagerly

Jenkinsfile
=> added downstream dependencies

release.groovy
lets use the fabric8-maven-dependences project to update all the quickstarts
=> lets use the fabric8-maven-dependences project to update all the quickstarts

core/src/main/java/io/fabric8/maven/core/access/ClusterAccess.java, core/src/main/java/io/fabric8/maven/core/access/KubernetesAccess.java, core/src/main/java/io/fabric8/maven/core/config/PlatformMode.java, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/AbstractAccessFabric8Mojo.java, plugin/src/main/java/io/fabric8/maven/plugin/AbstractFabric8Mojo.java, plugin/src/main/java/io/fabric8/maven/plugin/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/DeployMojo.java, samples/spring-boot/pom.xml
This is an initial work, waiting for some update in the kubernetes-client API
Please dont merge yet, needs some discussion and further work from the kubernetes-client API.
=> Initial support for binary source builds.

core/src/main/java/io/fabric8/maven/core/util/Configs.java, core/src/main/java/io/fabric8/maven/core/util/PrefixedLogger.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/AbstractLiveEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/build/src/main/java/io/fabric8/maven/enricher/build/BuildEnricher.java, enricher/dependency/src/main/java/io/fabric8/maven/enricher/dependency/DependencyEnricher.java, parent/pom.xml
TODO: There should be a more specific datum to decide whether the build is running in an Fabric8 CD environment or not.
BUILD_ID is to generic as it is set for every Jenkins build.
=> Tuned BuildEnricher with respect to offline mode

enricher/cd/src/main/java/io/fabric8/maven/enricher/cd/DocLinkEnricher.java, enricher/cd/src/main/java/io/fabric8/maven/enricher/cd/GrafanaLinkEnricher.java, enricher/cd/src/main/resources/META-INF/fabric8/enricher-default.txt, enricher/icon/src/main/resources/META-INF/fabric8/enricher-default, enricher/misc/pom.xml, enricher/misc/src/main/java/io/fabric8/maven/enricher/misc/DeploymentAnnotationsToPodSpecEnricher.java, enricher/misc/src/main/resources/META-INF/fabric8/enricher-default.txt, parent/pom.xml, plugin/pom.xml, pom.xml
Still making my way through our testless codebase inorder to  harmonize things. The curse when writing documentation is not, to write the documentation but to too explain the inconsistencies.
I hereby apologize up front for any inconvenience happening.
Looking forward to fix the quickstarts tomorrow ;-)
=> Thursday bloody Thursday ♪♪

plugin/src/main/java/io/fabric8/maven/plugin/PushMojo.java
Still open is the handling with the configuration properties where they are all prefixed with 'docker.' which would be niced to be replaced with 'fabric8.'
=> Fix fabric8:push with generated image configs (like in the quickstarts)

core/src/main/java/io/fabric8/maven/core/config/MetaDataConfig.java, core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, core/src/main/java/io/fabric8/maven/core/handler/DeploymentHandler.java, core/src/main/java/io/fabric8/maven/core/handler/PodTemplateHandler.java, core/src/main/java/io/fabric8/maven/core/handler/ReplicaSetHandler.java, core/src/main/java/io/fabric8/maven/core/handler/ReplicationControllerHandler.java, core/src/main/java/io/fabric8/maven/core/handler/ServiceHandler.java, core/src/main/java/io/fabric8/maven/core/util/MapUtil.java, core/src/test/java/io/fabric8/maven/core/util/MapUtilTest.java, doc/src/main/asciidoc/inc/_fabric8-build.adoc, doc/src/main/asciidoc/inc/_fabric8-resource.adoc, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/Kind.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ProjectEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ServiceEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/MetadataEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/MetadataVisitor.java, samples/spring-boot/pom.xml
+ added documentation for this.
TODO: Add labels and annotations also to profiles.
=> Implementes <labels> and <annotations> XML configuration.

core/src/main/java/io/fabric8/maven/core/config/BuildRecreateMode.java, doc/src/main/asciidoc/inc/_fabric8-build.adoc, plugin/src/main/java/io/fabric8/maven/plugin/BuildMojo.java
It that case everythin is recreated.
=> Allow for a default value for `fabric8.build.recreate` when no value given

README.md
versioneye dependencies badge didn't seem to be working.
=> dependencyci.com badge

core/src/main/java/io/fabric8/maven/core/util/Configs.java, doc/src/main/asciidoc/inc/_generator.adoc, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherConfig.java, generator/api/src/main/java/io/fabric8/maven/generator/api/BaseGenerator.java, generator/api/src/main/java/io/fabric8/maven/generator/api/FromSelector.java, generator/api/src/main/java/io/fabric8/maven/generator/api/GeneratorConfig.java, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, generator/karaf/src/main/java/io/fabric8/maven/generator/karaf/KarafGenerator.java, generator/spring-boot/src/main/java/io/fabric8/maven/generator/springboot/SpringBootGenerator.java
=> Tuned generator naming, exposed common properties better in generators.

.gitignore
=> - ignore eclipse files

enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ControllerEnricher.java
Configuration merging seems a bit brittle.  This is the second occasion
where a default setting was not properly merged in.  I’ve also added a
reflective method to help merge over simple fields to try to get this
robust.
=> Fixes #295, Default securityContext and replicas settings were not copied over

enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/GitEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/IANAServicePortNameEnricher.java, generator/api/src/main/java/io/fabric8/maven/generator/api/FromSelector.java, plugin/src/main/java/io/fabric8/maven/plugin/MapHandler.java, samples/spring-boot/pom.xml
- changed "f8-service" to "fmp-service" as enricher name
- some formatting of messages
- detection of redhat version can fail if no plugin is configured
=> Minor cleanups

core/src/main/java/io/fabric8/maven/core/util/ClassUtil.java, core/src/main/java/io/fabric8/maven/core/util/PluginServiceFactory.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java, plugin/src/main/java/io/fabric8/maven/plugin/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/PushMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/WatchMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, plugin/src/main/java/io/fabric8/maven/plugin/generator/GeneratorManager.java, plugin/src/main/resources/META-INF/fabric8/profiles.yml
This is only an example file. We should discuss which kind of profiles we would like to deliver. E.g. there should be something like a "pure" profile which does not enhance with fabric8 specific annotations. Other profiles could select specific generators only. Suggestions for profiles are highly appreciated.
=> Started to add default profiles

core/src/main/java/io/fabric8/maven/core/access/ClusterAccess.java, plugin/src/main/java/io/fabric8/maven/plugin/BuildMojo.java
Fixes for OSFUSE-282 (https://issues.jboss.org/browse/OSFUSE-282)
=> No Docker Access required for OpenShift builds

generator/api/src/main/java/io/fabric8/maven/generator/api/support/JavaRunGenerator.java, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, generator/wildfly-swarm/src/main/java/io/fabric8/maven/generator/wildflyswarm/WildFlySwarmGenerator.java
See also #320. Should be removed when logging issue with agent bond and wildfly swarm is resolved
=> Add workaround for agent bond to wildfly swarm generator

core/src/main/java/io/fabric8/maven/core/util/Gofabric8Util.java, parent/pom.xml
=> Convert Docker Host URL properly

core/src/main/java/io/fabric8/maven/core/util/Gofabric8Util.java, parent/pom.xml
requires d-m-p 0.16.5 which just has been released.
Fixes #333
=> Fix for missing cert lookup

generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/handler/AbstractAppServerHandler.java
https://github.com/fabric8io/fabric8-maven-plugin/blob/master/generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/handler/AbstractAppServerHandler.java#L24-L29 , need to be check for null as the some tasks can be done even before one build was done
=> Fix for Issue#492

generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/WebAppGenerator.java, generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/handler/AbstractAppServerHandler.java
This e.g. avoid an issue with scanning directories even when this generator is not
ative.
=> Make WebAppGenerator stateless

plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/AbstractInstallMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/ClusterStartMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/ClusterStopMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/InstallMojo.java
Stabilized download of gofabric8 binary
Still todo:
- Progressbar for download
- Checksum handling
=> Cleanup round for cluster-start

generator/spring-boot/src/main/java/io/fabric8/maven/generator/springboot/SpringBootGenerator.java, samples/spring-boot/pom.xml
Set it to 'always' to get color output in the console
=> Add config 'color' for spring-boot generator

core/src/main/java/io/fabric8/maven/core/util/IoUtil.java
=> Minor minor update to progress bar

core/src/main/java/io/fabric8/maven/core/util/ProcessUtil.java
thanks @davsclaus for the catch!
=> removed dodgy imports IDEA added!

core/src/main/java/io/fabric8/maven/core/config/ServiceConfig.java, core/src/main/java/io/fabric8/maven/core/config/ServiceProtocol.java, core/src/main/java/io/fabric8/maven/core/handler/ServiceHandler.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java, parent/pom.xml
=> Parse port protocol case insentive when given as config, always use uppercase when creating spec

core/src/main/java/io/fabric8/maven/core/config/ProcessorConfig.java, core/src/main/java/io/fabric8/maven/core/util/ProfileUtil.java, core/src/test/java/io/fabric8/maven/core/config/ProcessorConfigTest.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherConfig.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/ExposeEnricher.java, generator/api/src/main/java/io/fabric8/maven/generator/api/GeneratorConfig.java, plugin/src/main/resources/META-INF/fabric8/profiles.yml, plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java, samples/yaml-only/pom.xml, samples/yaml-only/src/main/fabric8/password-secret.yml
=> Fixing the 'raw' and 'internal-microservice' profiles

core/src/main/java/io/fabric8/maven/core/util/ResourceFileType.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/IconEnricher.java, parent/pom.xml, plugin/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/resources/META-INF/fabric8/profiles.yml
- tuned logging of icon-enricher, removed unnecessary field state
=> Various fixes + upgrade to d-m-p 0.17.1

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/main/java/io/fabric8/maven/core/util/OpenShiftDependencyResources.java, core/src/main/java/io/fabric8/maven/core/util/ProcessUtil.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/AbstractLiveEnricher.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/DocLinkEnricher.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/IconEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DependencyEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/MergeEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/OpenShiftS2IEnricher.java, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/AbstractResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/AppCatalogMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/AbstractTailLogMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/WatchMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/WatchSpringBootMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/AbstractInstallMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/ImportMojo.java
Fixed up lots calls but needs more review.
=> Fix for OSFUSE-425: First arg of log methods should be String format constant string.

core/src/main/java/io/fabric8/maven/core/util/Constants.java, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/VolumePermissionEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Moved init container handling to a dedicated enricher
=> Moved init container which chmod for persistent volumes to a dedicated enricher

CHANGELOG.md, doc/src/main/asciidoc/inc/generator/_webapp.adoc, generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/WebAppGenerator.java, pom.xml
Its documented in the CHANGELOG.md
=> Streamlining some configuration names.

core/src/main/java/io/fabric8/maven/core/util/Constants.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/main/java/io/fabric8/maven/core/util/OpenShiftDependencyResources.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/AbstractLiveEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/PrometheusEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DependencyEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/MergeEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/OpenShiftS2IEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/RemoveBuildAnnotationsEnricher.java, generator/api/src/main/java/io/fabric8/maven/generator/api/GeneratorContext.java, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentConfigOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/AppCatalogMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java
=> Refactored EnricherContext to use a builder pattern

generator/vertx/src/main/java/io/fabric8/maven/generator/vertx/VertxGenerator.java, generator/vertx/src/main/resources/META-INF/fabric8/generator-default, parent/pom.xml, plugin/pom.xml
A very simple generator for Vert.x project.
=> Initial version of the Vert.x Generator

samples/external-resources/pom.xml, samples/spring-boot-with-yaml/pom.xml, samples/spring-boot/pom.xml, samples/webapp-jetty/pom.xml, samples/webapp-wildfly/pom.xml, samples/webapp/pom.xml, samples/yaml-only/pom.xml, samples/zero-config/pom.xml
fabric8-maven-sample-eng left behind as there are other issues with
spring-boot-generator-jersey
=> Update samples to 3.2-SNAPSHOT

plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/AppCatalogMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/WatchMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/AbstractInstallMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/HelmIndexMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/ManifestIndexMojo.java, plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java
- use genericity
- remove unused variable
- avoid NPE
=> Clean code

enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java
This is of course a breaking change - I think it's the right thing to do though.
Fixes #693
=> Remove default service type

it/pom.xml, it/src/it/settings.xml, it/src/it/simple/expected/kubernetes.yml, it/src/it/simple/invoker.properties, it/src/it/simple/pom.xml, it/src/it/simple/src/main/java/zero/Application.java, it/src/it/simple/src/main/java/zero/HelloController.java, it/src/it/simple/verify.groovy, it/src/test/java/io/fabric8/maven/it/Verify.java, parent/pom.xml, pom.xml
Shamlessly stolen from vertx-maven-plugin ;-)
It use Citrus for doing more relaxed validation so that values can be ignored, too.
=> Initial setup for f-m-p integration tests

it/src/it/simple/expected/kubernetes.yml, it/src/test/java/io/fabric8/maven/it/Verify.java
These are described here: http://www.citrusframework.org/reference/html/validation-matchers.html#validation-matcher
=> Add support Citrus validation matchers

doc/src/main/asciidoc/inc/_enricher.adoc, doc/src/main/asciidoc/inc/generator/_vertx.adoc, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/VertxHealthCheckEnricher.java, enricher/fabric8/src/main/resources/META-INF/fabric8/enricher-default, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/VertxHealthCheckEnricherTest.java, generator/vertx/src/main/java/io/fabric8/maven/generator/vertx/VertxGenerator.java
* Add an enricher to add health checks to Vert.x applications
* Add documentation about the Vert.x generator
* Add documentation about the enricher
* Small improvements of the generator
=> improve vertx generator and enricher

core/src/main/java/io/fabric8/maven/core/util/PluginServiceFactory.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/PrometheusEnricher.java, enricher/fabric8/src/main/resources/META-INF/fabric8/enricher-default, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default
* Backport of important fix for lookup of enricher entries with the same order number
* added explicit order number to every enricher to ensure consistent enricher order
* minor update for PrometheusEnricher
=> Backport of important fix for lookup of enricher entries

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java
When using this flag, the only precondition is now that only a single service is exposed.
Relates to https://issues.jboss.org/browse/OSFUSE-479
Fixes #756.
=> OSFUSE-479: Add route for fabric8.deploy.createExternalUrls for OpenShift regardless of Service Type

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java
Related to https://issues.jboss.org/browse/OSFUSE-416
=> Better error message when parsing of a fragment fails

core/src/main/java/io/fabric8/maven/core/config/OpenShiftBuildStrategy.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, doc/src/main/asciidoc/inc/generator/_java_exec.adoc, doc/src/main/asciidoc/inc/generator/_karaf.adoc, doc/src/main/asciidoc/inc/generator/_options_common.adoc, generator/api/src/main/java/io/fabric8/maven/generator/api/FromSelector.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java, generator/api/src/main/resources-filtered/META-INF/fabric8/default-images.properties, generator/api/src/test/java/io/fabric8/maven/generator/api/FromSelectorTest.java, generator/api/src/test/java/io/fabric8/maven/generator/api/support/BaseGeneratorTest.java, generator/api/src/test/resources/META-INF/fabric8/default-images.properties, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, generator/karaf/src/main/java/io/fabric8/maven/generator/karaf/KarafGenerator.java, generator/karaf/src/main/resources-filtered/META-INF/fabric8/default-images.properties, generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/WebAppGenerator.java, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
Relevant issues:
https://issues.jboss.org/browse/OSFUSE-283
https://issues.jboss.org/browse/OSFUSE-428
https://issues.jboss.org/browse/OSFUSE-416
=> Fixes from v3.1.80-redhat branch, updated for "master"

core/pom.xml, core/src/main/java/io/fabric8/maven/core/service/ImageStreamService.java, core/src/main/java/io/fabric8/maven/core/util/ResourceFileType.java, core/src/test/java/io/fabric8/maven/core/service/ImageStreamServiceTest.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java, generator/api/src/test/java/io/fabric8/maven/generator/api/support/BaseGeneratorTest.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
This is a backport of #782 to v3.1.80-redhat
=> Make writing of the imagestream tags created to resource file optional

core/src/main/java/io/fabric8/maven/core/openshift/BuildService.java, core/src/main/java/io/fabric8/maven/core/openshift/ImageStreamService.java, core/src/main/java/io/fabric8/maven/core/openshift/OpenShiftBuildService.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/openshift/ImageStreamServiceTest.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/AbstractTailLogMojo.java
This also is related to https://issues.jboss.org/projects/OSFUSE/issues/OSFUSE-483
=> Started to move out OpenShift build things to an external service.

core/src/main/java/io/fabric8/maven/core/openshift/BuildService.java, core/src/main/java/io/fabric8/maven/core/openshift/ImageStreamService.java, core/src/main/java/io/fabric8/maven/core/openshift/OpenShiftBuildService.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/openshift/ImageStreamServiceTest.java, doc/src/main/asciidoc/inc/generator/_java_exec.adoc, generator/api/src/main/java/io/fabric8/maven/generator/api/FromSelector.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java, generator/api/src/main/resources-filtered/META-INF/fabric8/default-images.properties, generator/api/src/test/java/io/fabric8/maven/generator/api/support/BaseGeneratorTest.java, generator/java-exec/src/test/java/io/fabric8/maven/generator/javaexec/JavaExecGeneratorMainClassDeterminationTest.java, generator/karaf/src/main/resources-filtered/META-INF/fabric8/default-images.properties, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/AbstractTailLogMojo.java
These are the upstream ports of #785 and #784
=> Redhat branch ports

core/src/main/java/io/fabric8/maven/core/util/JSONUtil.java, core/src/test/java/io/fabric8/maven/core/util/JSONUtilTest.java, enricher/api/pom.xml, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/util/InitContainerHandler.java, enricher/api/src/test/java/io/fabric8/maven/enricher/api/util/InitContainerHandlerTest.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/AutoTLSEnricher.java, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AutoTLSEnricherTest.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/GitEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/VolumePermissionEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/VolumePermissionEnricherTest.java, parent/pom.xml, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
+ be silent when no git enrichment can be performed when not within a git based project.
=> Fixed for #806 / #807

core/src/main/java/io/fabric8/maven/core/handler/HandlerHub.java, core/src/main/java/io/fabric8/maven/core/handler/JobHandler.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/Kind.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ProjectEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/MetadataVisitor.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java
Similar to my PR for issue #517, I've made the changes required to create Job resources. 
The following XML snippet seems to generate Job resources, with this change.
```
<enricher>
<config>
<fmp-controller>
<type>job</type>
</fmp-controller>
</config>
</enricher>
```
=> Added support for Job resources

README.md, generator/webapp/src/main/resources/assemblies/webapp.xml, samples/webapp-wildfly/pom.xml
=> Fix webapp assembly descriptor

core/src/main/java/io/fabric8/maven/core/config/ProcessorConfig.java, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherConfig.java, samples/custom-enricher/app/pom.xml, samples/custom-enricher/app/src/main/fabric8/deployment.yml, samples/custom-enricher/app/src/main/java/io/fabric8/maven/sample/enricher/app/Application.java, samples/custom-enricher/app/src/main/java/io/fabric8/maven/sample/enricher/app/HelloController.java, samples/custom-enricher/app/src/main/secret_data.txt, samples/custom-enricher/pom.xml, samples/custom-enricher/secret-enricher/pom.xml, samples/custom-enricher/secret-enricher/src/main/java/io/fabric8/maven/sample/enricher/secret/SecretEnricher.java, samples/custom-enricher/secret-enricher/src/main/resources/META-INF/fabric8/enricher
and updated base enricher class a bit
=> Added custom enricher example

plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
This is a Swarm counterpart to https://github.com/fabric8io/fabric8-maven-plugin/pull/927
=> readd WildFly Swarm healthcheck which was missing

enricher/api/src/main/java/io/fabric8/maven/enricher/api/Kind.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ProjectEnricher.java, it/src/it/deployment-strategy-type-919/expected/openshift.yml, it/src/it/simple/verify.groovy, it/src/it/spring-boot/verify.groovy, plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java, samples/spring-boot/pom.xml
=> Fix bogus version in deployment selector.

plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java
fixes #966 to allow a timeoutSeconds to be specified on the Deployment and populated on a DeploymentConfig
=> fix(timeoutSeconds): allow population on DeploymentConfig

core/src/main/java/io/fabric8/maven/core/service/ClientToolsService.java, generator/karaf/src/main/resources/assemblies/karaf.xml
=> OSFUSE-552: ensure all fixes from FIS 2.0 branches have been merged to master

enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DependencyEnricher.java
lets preserve template parameter expressions in kubernetes dependencies
=> fixes #978

core/src/main/java/io/fabric8/maven/core/openshift/BuildService.java
It seems that in Openshift 3.7 binary builds return a HTTP response only when the build is finished. Before 3.7, a build object was returned immediately, allowing us to do tail log.
The late response make chances of blocking indefinitely much higher, because the build may be already finished by the time we start watching on the "finish" event.
This should affect also the "master" branch.
=> OSFUSE-605: build may be already finished in Openshift 3.7

core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java
=> Fix build error

core/src/main/java/io/fabric8/maven/core/util/SpringBootProperties.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/SpringBootHealthCheckEnricher.java, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/SpringBootHealthCheckEnricherTest.java, watcher/standard/src/main/java/io/fabric8/maven/watcher/standard/SpringBootWatcher.java
I've added fixed most of the configuration cases involving server context path, management context path, servlet path, management key store and server key store.
=> Fixes #965 by improving spring-boot probes

doc/src/main/resources/META-INF/services/org.asciidoctor.extension.spi.ExtensionRegistry, generator/api/src/test/java/io/fabric8/maven/generator/api/support/BaseGeneratorTest.java, generator/spring-boot/src/test/java/io/fabric8/maven/generator/springboot/SpringBootGeneratorTest.java, it/src/test/java/io/fabric8/maven/it/Verify.java
=> Cleaning up licenses

enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/RevisionHistoryEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/RevisionHistoryEnricherTest.java
Accommodate minor review changes from https://github.com/fabric8io/fabric8-maven-plugin/pull/1025/files/ee2dbd348ce2c364f394c8c188c4773eb4a5efab#diff-6cdf58b53e8707096bf08495bf352200R55
=> Minor review changes for revision history 

it/src/it/revisionhistory/expected/kubernetes.yml, it/src/it/revisionhistory/expected/openshift.yml, it/src/it/revisionhistory/invoker.properties, it/src/it/revisionhistory/pom.xml, it/src/it/revisionhistory/src/main/java/io/fabric8/maven/sample/spring/boot/Application.java, it/src/it/revisionhistory/src/main/java/io/fabric8/maven/sample/spring/boot/HelloController.java, it/src/it/revisionhistory/verify.groovy
Added integration test for #1017
=> Integration test for revision history limit

core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java, doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
@hrishin I'd appreciate if you can take a look at this.
Fixes #1040.
=> Turning validation errors into warnings

core/src/main/java/io/fabric8/maven/core/util/validator/ResourceValidator.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
lets avoid NPEs and avoid validating directories
=> fixes #1044 regression of new validation code in 3.5.28

core/src/main/java/io/fabric8/maven/core/config/HelmConfig.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/HelmMojo.java
so that any OpenShift Template expressions are turned into their Helm chart equivalent
=> support generation of parameterised helm charts

it/src/it/fabric8-jenkins-github/expected/k8s-template.yml, it/src/it/fabric8-jenkins-github/pom.xml
=> fixed the dependency issue

it/src/it/fabric8-jenkins-github/expected/k8s-template.yml
=> fixed the IT issue

core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java
doing watchLog() straightway seems to causing problems on OpenShift 3.7.0,
let's watch over the build pod until it's ready.
=> Fix #1132 build logs and status is not working with OpenShift

rt/src/test/java/io/fabric8/maven/rt/BaseBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxHttpBoosterIT.java
+ Added a try catch block around makeHttpRequest(..); in case nip.io is down
+ Added retry() logic while checking vertx-http-booster's endpoints.
=> Fix #1149 : Handle problems in fmp regression tests

core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java
Handle intermittent Socket timeout build issues happening on
OpenShift build service.
=> Fix #1133 build timeout for OpenShift build service

Jenkinsfile, release.groovy
Also in CD process we are generating tags and then doing
build, test and release
I have added commands to run test and build before
generating tags because sometimes tag got pushed but due to
some test failure it will not get released.
#1166 
#1158
=> Fixes Jenkins file for better release process

core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java
+ Handle Socket exception intermittently occurring in tests, and
retry few times.
+ Added some logging in the test for better understanding of failure.
Fixes #1162
=> Fix #1162 : OpenShiftBuildServiceTest failing intermittently on CI

rt/src/test/java/io/fabric8/maven/rt/BaseBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootCrudBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootHttpBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxConfigmapBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxHealthchecksBooster.java, rt/src/test/java/io/fabric8/maven/rt/VertxHttpBoosterIT.java
=> Fix regression tests in order to get them working on Openshift 3.7 #1188

Jenkinsfile
=> Update Jenkins as it is throwing error during release

.gitignore, core/src/main/java/io/fabric8/maven/core/util/FileUtil.java, core/src/test/java/io/fabric8/maven/core/util/ClassUtilTest.java, generator/api/src/test/java/io/fabric8/maven/generator/api/support/AbstractPortsExtractorTest.java, generator/api/src/test/resources/io/fabric8/maven/generator/api/support/AbstractPortsExtractorTest++suffix.yaml, generator/java-exec/src/test/java/io/fabric8/maven/generator/javaexec/FatJarDetectorTest.java, generator/vertx/src/test/java/io/fabric8/maven/generator/vertx/VertxPortsExtractorTest.java
Fix the unit tests of the project in order to successfully run on Windows (there were few problems with Windows' file path separator and a disk name letter). I'm not sure whether the committers are interested in the ability to build the project on Windows but if you have any question regarding the PR, please, be free to ask them.
=> Fix unit tests on Windows

plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/AbstractInstallMojo.java
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> #1100 - Fix startup script for windows

README.md
Added the links of TravisCI and Jenkins
Anyone can view the recent build logs.
=> Update README.md to add the links to recent builds

CHANGELOG.md, doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, doc/src/main/asciidoc/inc/goals/develop/_fabric8-deploy.adoc, it/src/it/simple-with-route-flag-false/expected/kubernetes.yml, it/src/it/simple-with-route-flag-false/expected/openshift.yml, it/src/it/simple-with-route-flag-false/invoker.properties, it/src/it/simple-with-route-flag-false/pom.xml, it/src/it/simple-with-route-flag-false/src/main/java/zero/Application.java, it/src/it/simple-with-route-flag-false/src/main/java/zero/HelloController.java, it/src/it/simple-with-route-flag-false/verify.groovy, it/src/it/simple-with-route-flag-true/expected/kubernetes.yml, it/src/it/simple-with-route-flag-true/expected/openshift.yml, it/src/it/simple-with-route-flag-true/invoker.properties, it/src/it/simple-with-route-flag-true/pom.xml, it/src/it/simple-with-route-flag-true/src/main/java/zero/Application.java, it/src/it/simple-with-route-flag-true/src/main/java/zero/HelloController.java, it/src/it/simple-with-route-flag-true/verify.groovy, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/AbstractResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/AppCatalogMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, samples/spring-boot-without-route/pom.xml, samples/spring-boot-without-route/src/main/deployments/bin/test.sh, samples/spring-boot-without-route/src/main/java/io/fabric8/maven/sample/spring/boot/Application.java, samples/spring-boot-without-route/src/main/java/io/fabric8/maven/sample/spring/boot/HelloController.java
if fabric8.openshift.generateRoute is set to false no route.yaml will be generated and if set true or not set it will generate route.yml
#1209
=> Adds flag for Route Generation

CHANGELOG.md, doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentConfigOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/KubernetesToOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/NamespaceOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/ReplicSetOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Added fabric8.openshift.setDeploymentTriggerAutomatic flag which would
be able to enable/disable automatic deployments.
#1177
=> Fixes #1177 Minor changes to ImageTrigger generation

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/openshift/ImageStreamService.java, core/src/test/java/io/fabric8/maven/core/service/openshift/ImageStreamServiceTest.java
- fixes ImageStream service to pick the version of image SHA to reflect latest version to S2I build
fix https://github.com/openshiftio/openshift.io/issues/2505
=> fix 2505 : Pipeline fails to deploy changes to an application

Jenkinsfile
This will revert the changes made in #1218 
#1195
=> This will revert the changes made to Jenkins file

core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java
Added exception handling cases in other tests also using OpenShiftMockServer.
Initlially it was in testSuccessfulBuild() only.
=> Fix #1162 Fix OpenshiftBuildServiceTest intermittent failures on CI

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/HelmConfig.java, doc/src/main/asciidoc/inc/goals/build/_fabric8-helm.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/HelmMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/HelmIndexMojo.java
=> [Issue-1231] Fix helm artifact extension to "*.tgz"

Jenkinsfile
#1195 
Two different containers - one for testing and one for stage and promote.Hope this will work. Fork master got build here : https://jenkins.cd.test.fabric8.io/view/all/job/fmp%20Piyush/6/console
=> Again trying to run test before generating tags

doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc
Fix Docs as website (http://maven.fabric8.io) is not getting rendered properly
=> Fix Docs as website is not getting rendered properly

README.md, doc/src/main/asciidoc/inc/_compatibility.adoc, doc/src/main/asciidoc/index.adoc
Added OpenShift and Kubernetes version Compatibility Matrix both in the README and Website Docs.
Created a new section Compatibility with Openshift and Kubernetes in website. 
#1207
=> Added OpenShift and Kubernetes version Compatibility Matrix

doc/src/main/asciidoc/inc/_compatibility.adoc
This will fix the extra column generated here https://maven.fabric8.io/#compatibility-with-OpenShift-and-Kubernetes
=> Fix extra column generated

rt/src/test/java/io/fabric8/maven/rt/BaseBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java
Spring boot Configmap Booster in a multimodule project so it required fmp version as a command line argument too
Otherwise, it is fetching the latest version for other modules
=> Refactor Regression Tests

rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootCrudBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootHttpBoosterIT.java
=> Fixes url to static in RT as this has been fixed in catalogue

README.md, doc/src/main/asciidoc/inc/_compatibility.adoc
=> Updated compatability matrix with OpenShift 3.9.0

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/Profile.java, core/src/main/java/io/fabric8/maven/core/util/ProfileUtil.java, core/src/test/java/io/fabric8/maven/core/util/ProfileUtilTest.java, core/src/test/resources/fabric8/config/profiles-lookup-dir/profiles.yaml, doc/src/main/asciidoc/inc/_profiles.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
=> Fix #886 : Introduce extends for profiles

core/src/main/java/io/fabric8/maven/core/util/MavenUtil.java
- droped unsed method that coulod cause CEV issue
=> fixed unizp issue

CHANGELOG.md, doc/src/main/asciidoc/inc/_enricher.adoc, doc/src/main/asciidoc/inc/_generator.adoc, doc/src/main/asciidoc/inc/generator/_thorntail_v2.adoc, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/IconEnricher.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/ThorntailV2HealthCheckEnricher.java, enricher/fabric8/src/main/resources/META-INF/fabric8/enricher-default, generator/karaf/src/main/resources/META-INF/fabric8/generator-default, generator/spring-boot/src/main/resources/META-INF/fabric8/generator-default, generator/thorntail-v2/pom.xml, generator/thorntail-v2/src/main/java/io/fabric8/maven/generator/thorntail/v2/ThorntailV2Generator.java, generator/thorntail-v2/src/main/resources/META-INF/fabric8/generator-default, generator/vertx/src/main/resources/META-INF/fabric8/generator-default, generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/handler/WildFlyAppSeverHandler.java, generator/webapp/src/test/java/io.fabric8.maven.generator.webapp/AppServerAutoDetectionTest.java, generator/wildfly-swarm/src/main/resources/META-INF/fabric8/generator-default, parent/pom.xml, plugin/pom.xml, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml, pom.xml
This adds a new `thorntail-v2` generator, as a slightly edited copy
of the `wildfly-swarm` generator, and a `thorntail-v2-health-check`
enricher, again as a copy of the `wildfly-swarm-health-check`
enricher. The reason for adding the `v2` suffix is that there
is already a Thorntail v4 prototype, and that's a complete
rearchitecture.
=> Fix 1298: WildFly Swarm was renamed to Thorntail

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/JSONUtil.java, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/TriggersAnnotationEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/TriggersAnnotationEnricherTest.java, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
This will fix #1291.
Change does not affect standard deployments.
=> Add ImageStreamTag change trigger for Kubernetes resources

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/HelmMojo.java
=> Preserve file extension when copying the file to helm chart folder

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/MavenUtil.java, core/src/main/java/io/fabric8/maven/core/util/SpringBootConfigurationHelper.java, generator/spring-boot/src/main/java/io/fabric8/maven/generator/springboot/SpringBootGenerator.java, generator/spring-boot/src/test/java/io/fabric8/maven/generator/springboot/SpringBootGeneratorTest.java, watcher/standard/src/main/java/io/fabric8/maven/watcher/standard/SpringBootWatcher.java
#1340 Fixes situations where the plugin is repackaged.
=> spring-boot-maven-plugin is detected under any groupId

parent/pom.xml, samples/spring-boot-with-yaml/pom.xml
These also include a Java update to 1.8.0_181 (from _161)
=> feature: Update default base images to their latest versions

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
=> Fixes the typo: Identical conditions on both side of OR operator.

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java
=> Avoids empty deployment selector value in generated yaml resource

doc/src/main/asciidoc/inc/_introduction.adoc
Path to util class changed but docs weren't updated.
=> Fix url for listing of resource kind mappings

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/SpringBootUtil.java, core/src/test/java/io/fabric8/maven/core/util/SpringBootUtilTest.java, core/src/test/resources/util/invalid-application.yml
#1390 Provides better exception message in case of invalid  in Spring Boot
=> fix(#1390): Provides better exception message in parsing error

CHANGELOG.md, core/pom.xml, core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java, core/src/main/java/io/fabric8/maven/core/service/BuildService.java, core/src/main/java/io/fabric8/maven/core/service/kubernetes/DockerBuildService.java, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, core/src/test/java/io/fabric8/maven/core/service/kubernetes/DockerBuildServiceTest.java, enricher/api/pom.xml, enricher/fabric8/pom.xml, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/DockerHealthCheckEnricherTest.java, enricher/osio/pom.xml, generator/api/pom.xml, generator/java-exec/pom.xml, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, generator/karaf/src/main/java/io/fabric8/maven/generator/karaf/KarafGenerator.java, generator/spring-boot/pom.xml, generator/webapp/pom.xml, generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/WebAppGenerator.java, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
=> Fix #1327 : Upgrade d-m-p

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java, core/src/test/java/io/fabric8/maven/core/handler/ContainerHandlerTest.java, core/src/test/java/io/fabric8/maven/core/handler/PodTemplateHandlerTest.java, it/src/it/docker-health-checks/expected/kubernetes.yml, it/src/it/docker-health-checks/expected/openshift.yml, samples/xml-config/pom.xml
=> Fix #1365: Generated image reference in *-deployment.yml contains duplicate registry name

.github/stale.yml
=> Add github-stale bot.

.gitignore, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/ServiceDiscoveryEnricher.java, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/ServiceDiscoveryEnricherTest.java, parent/pom.xml
=> 3.5.x - [fix] Apply updates to the new discovery.3scale.net labels/annotations

.circleci/config.yml, .github/stale.yml, core/src/main/java/io/fabric8/maven/core/config/MappingConfig.java, core/src/main/java/io/fabric8/maven/core/model/Artifact.java, core/src/main/java/io/fabric8/maven/core/util/PropertiesMappingParser.java, core/src/test/java/io/fabric8/maven/core/util/PropertiesMappingParserTest.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/Dependency.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/DockerRegistryAuthentication.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/util/MavenConfigurationExtractor.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/util/ProjectClassLoader.java, enricher/api/src/test/java/io/fabric8/maven/enricher/api/util/MavenConfigurationExtractorTest.java, enricher/deprecated/pom.xml, enricher/deprecated/src/main/java/io/fabric8/maven/enricher/deprecated/DocLinkEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DebugEnricher.java, it/src/it/custom-raw-resources/expected/kubernetes.yml, it/src/it/custom-raw-resources/expected/openshift.yml, it/src/it/custom-raw-resources/pom.xml, it/src/it/custom-raw-resources/src/main/fabric8/raw/sample-foo.yml, it/src/it/custom-raw-resources/verify.groovy, parent/pom.xml, plugin/src/test/java/io/fabric8/maven/plugin/mojo/build/MappingConfigTest.java, plugin/src/test/resources/mojo/build/mapping-mojo-config.xml
+ Updated Kubernetes-client to v4.0.7
+ Added license check in circleci
=> Update kubernetes client to v4.0.7

.circleci/config.yml
Use machine build instead of docker executor which is breaking right now
=> Fix CircleCI breaking build

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/GitEnricher.java
=> fix(#314): Do not execute GitEnricher if not Git repo.

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ConfigMap.java, core/src/main/java/io/fabric8/maven/core/config/ConfigMapEntry.java, core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ConfigMapEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/ConfigMapEnricherTest.java, enricher/standard/src/test/resources/test-application.properties, it/src/it/configmap/expected/kubernetes.yml, it/src/it/configmap/expected/openshift.yml, it/src/it/configmap/invoker.properties, it/src/it/configmap/pom.xml, it/src/it/configmap/src/main/java/zero/Application.java, it/src/it/configmap/src/main/java/zero/HelloController.java, it/src/it/configmap/verify.groovy, plugin/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml, plugin/src/test/java/io/fabric8/maven/plugin/mojo/build/ResourceMojoTest.java, plugin/src/test/resources/test-application.properties
=> feat(#977): Allows user to define ConfigMap from XML and annotation

CHANGELOG.md, core/src/main/resources/META-INF/fabric8/kind-filename-type-mapping-default.adoc, core/src/test/java/io/fabric8/maven/core/util/kubernetes/KindFilenameMapperUtilTest.java
=> fixes 963: add support for Pod resource type in yaml config

README.md
This updates compatability matrix too #1356
=> Chore: Minor improvements in README

plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java
=> Fixes overriding of SpecSelector MatchLabel entries by the enrichers entries.

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
=> Chore #796: Remove workaround to produce both .yaml and .json files

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java
=> Fix #1412: Extract fromName from Dockerfile when build is Dockerfile based

CHANGELOG.md, enricher/api/src/main/java/io/fabric8/maven/enricher/api/Kind.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/MetadataVisitor.java
=> Added metadata visitors for imagestreams, build and buildconfig.

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/VolumeConfig.java, core/src/main/java/io/fabric8/maven/core/config/VolumeType.java, doc/src/main/asciidoc/inc/volumes.adoc, doc/src/main/asciidoc/index.adoc, samples/xml-config/pom.xml
Fix #10 : Added more volume types to VolumeConfig
=> Fix #10: VolumeConfiguration more flexible

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ProbeConfig.java, core/src/main/java/io/fabric8/maven/core/handler/ProbeHandler.java, core/src/test/java/io/fabric8/maven/core/handler/ProbeHandlerTest.java, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/KarafHealthCheckEnricher.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/SpringBootHealthCheckEnricher.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/ThorntailV2HealthCheckEnricher.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/WildFlySwarmHealthCheckEnricher.java, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AbstractSpringBootHealthCheckEnricherTestSupport.java
=> Fix #1373: Allow the configuration of failureThreshold and successThreshold on readiness and liveness probes

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ControllerViaPluginConfigurationEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
=> Fix #401: Refactor DefaultControllerEnricher

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java, core/src/main/java/io/fabric8/maven/core/handler/ProbeHandler.java, core/src/test/java/io/fabric8/maven/core/handler/ProbeHandlerTest.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, it/src/it/env-metadata/expected/kubernetes.yml, it/src/it/env-metadata/expected/openshift.yml
Fix #1019: Added CustomProbeEnricher for adding probes via XML config
=> Fix #1019: Custom Liveness/Readiness probes are not being created

CHANGELOG.md, doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, it/src/it/custom-environment/expected/kubernetes.yml, it/src/it/custom-environment/expected/openshift.yml, it/src/it/custom-environment/invoker.properties, it/src/it/custom-environment/pom.xml, it/src/it/custom-environment/src/main/fabric8/dev/deployment.yaml, it/src/it/custom-environment/src/main/java/io/vertx/example/SimpleWebVerticle.java, it/src/it/custom-environment/verify.groovy, plugin/src/main/java/io/fabric8/maven/plugin/mojo/ResourceDirCreator.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/PushMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/WatchMojo.java
Fix #729 
Adds environment property so custom resources can be selected depending on the environment
=> feat(#729): Adds environment property 

core/src/main/java/io/fabric8/maven/core/service/PatchService.java, core/src/test/java/io/fabric8/maven/core/service/openshift/PatchServiceTest.java
Fixes #1475
Signed-off-by: bohmber <bommel@apache.org>
=> stringData secret should be checked during patching as well

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/BuildService.java, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
=> Added 'fabric8.build.forcePull' parameter.

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java
Fix #925 
XML properties(if set) should be given precedence over default ones.
=> Fix #925: Unable to configure replicas count via property

CHANGELOG.md, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/GitEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
=> Added Git URL to GitEnricher.

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, core/src/main/java/io/fabric8/maven/core/util/FileUtil.java, doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, it/src/it/remote-resources/expected/kubernetes.yml, it/src/it/remote-resources/expected/openshift.yml, it/src/it/remote-resources/invoker.properties, it/src/it/remote-resources/pom.xml, it/src/it/remote-resources/src/main/java/io/vertx/example/SimpleWebVerticle.java, it/src/it/remote-resources/verify.groovy, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
=> feat(#804): Allow set fragments as external references (URL)

README.md
=> Fix #1356: Updated compatibility matrix with latest kubernetes/Openshift versions

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/MapUtil.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/Enricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/util/ExtractorUtil.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/util/Misc.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/visitor/MetadataVisitor.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/visitor/SelectorVisitor.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultMetadataEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml, plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java
=> Refactor #828: Moved Metedata specific code into DefaultMetadataEnricher

.circleci/config.yml, doc/ci-docs.sh
=> add docs job

.circleci/config.yml, scripts/prepare-environment.sh, scripts/release.sh, scripts/utils.sh
=> Added Release workflow on CircleCI

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/access/ClusterConfiguration.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/WatchMojo.java
Changed default constructor to initialize namespace rather than doing
nothing
I found it out while trying to reproduce #1522
=> Fix NullPointerException in ClusterConfiguration while fabric8:watch

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
+ Fix NullPointerException in fabric8:build due to reference to properties
+ Re introduce RuntimeMode in ResourceMojo as it's causing problems with deployment on fmp
=> Fix regressions from resource post processing refactoring

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, core/src/main/java/io/fabric8/maven/core/config/ServiceAccountConfig.java, doc/src/main/asciidoc/inc/_enricher.adoc, doc/src/main/asciidoc/inc/_introduction.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ServiceAccountEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/ServiceAccountEnricherTest.java, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
=> Fix #931: Add ServiceAccount enricher and configuration

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/WatchMojo.java
Fixes #1522
No need to have DockerAccess initialized when on Openshift
=> Fix #1522: fabric8-watch fails

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/BuildLabelAnnotations.java, core/src/main/java/io/fabric8/maven/core/util/BuildLabelUtil.java, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, generator/karaf/src/main/java/io/fabric8/maven/generator/karaf/KarafGenerator.java, generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/WebAppGenerator.java
=> Feature 456 : Add labels from label-schema.org to the generator images

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java, it/src/it/custom-environment/expected/kubernetes.yml, it/src/it/remote-resources/expected/kubernetes.yml, it/src/it/statefulset/expected/kubernetes.yml, it/src/it/statefulset/expected/openshift.yml, it/src/it/vertx/expected/kubernetes.yml
Fix #1570 
Change API_APPS_VERSION to apps/v1 and move deployment fragment creation
with apps/v1 apiVersion rather than extensions
=> Fix #1570: change API_APPS_VERSION to apps/v1

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java
Fix #1578: Fixed my mistake while refactoring Converters into Enrichers
=> Fix #1578: Fmp is generating ImageChange triggers in the DeploymentConfig

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultMetadataEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java
=> Refactor EnricherManager

CHANGELOG.md, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ControllerViaPluginConfigurationEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java
Fix #1600 
Give preference to resource fragments rather than XML config. We were ignoring resource fragments value in controller enrichers.
=> Fix #1600: Replicas fragment not set

CHANGELOG.md, doc/src/main/asciidoc/inc/_introduction.adoc
=> Added documentation regarding new behavior for resource fragments when using sidecars

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DependencyEnricher.java
=> fix aggregation on OpenShift

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, core/src/main/java/io/fabric8/maven/core/handler/HandlerHub.java, core/src/main/java/io/fabric8/maven/core/handler/NamespaceHandler.java, core/src/main/java/io/fabric8/maven/core/handler/ProjectHandler.java, core/src/main/java/io/fabric8/maven/core/service/ApplyService.java, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java, doc/src/main/asciidoc/inc/_introduction.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultNamespaceEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ProjectLabelEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/ProjectEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/MavenProjectEnricherTest.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml, plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java, samples/spring-boot-with-yaml/pom.xml
Fixes #1608
Fixes #1611
Fixes #1470
=> Refactor for Namespace and Project

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, parent/pom.xml
=> Upgrade to Docker Maven Plugin 0.29.0

.circleci/config.yml, doc/ci-docs.sh, parent/pom.xml, scripts/utils.sh
It looks like current bot fabric8cd didn't had access to pushing to our
github repository, See:
https://circleci.com/gh/rohanKanojia/fabric8-maven-plugin/1215
So, I created a bot fabric8ci with access to our repository. Plus, I
added doc update to release section also since docs should be updated
along with release IMO.
=> Chore: Minor fixed in docs script

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java
=> Fix #1626 regression: NullPointerException in ApplyMojo

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/ResourceVersioning.java, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java
Fixes #1630 
Fixing CronJob version
=> Fixing #issue1630

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/ApplyService.java, core/src/main/java/io/fabric8/maven/core/service/PatchService.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ProjectLabelEnricher.java
=> Fix #1648: Job creation fails during fabric8:apply with error: forbidden

CHANGELOG.md, core/src/test/java/io/fabric8/maven/core/util/ProfileUtilTest.java, core/src/test/resources/META-INF/fabric8/profiles.yml, core/src/test/resources/fabric8/config/profiles-lookup-dir/profiles.yaml, doc/src/main/asciidoc/inc/_enricher.adoc, doc/src/main/asciidoc/inc/_profiles.adoc, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
=> Additions to Minimal profile

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ServiceConfig.java, doc/src/main/asciidoc/inc/_enricher.adoc, doc/src/main/asciidoc/inc/enricher/_fmp_service.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricherTest.java
=> added service port normalization

CHANGELOG.md, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ControllerViaPluginConfigurationEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/ImageChangeTriggerEnricher.java
No need to specify specific methods for every flag we add to plugin.
=> Chore: Minor refactor to avoid code duplication.

CHANGELOG.md, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java
=> Fix 1666: corrected back switchToDeployment flag functionality.

CHANGELOG.md, core/src/test/java/io/fabric8/maven/core/service/kubernetes/DockerBuildServiceTest.java
=> DockerBuildServiceTest Refactored

parent/pom.xml
Update docker-maven-plugin to latest release
=> Update docker-maven-plugin to 0.31.0

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/ApplyService.java, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java
=> Fix #1697: NullPointerException when applying custom resources

CHANGELOG.md, parent/pom.xml
=> Fix #1676: Support for latest kubernetes client

CHANGELOG.md, core/pom.xml, parent/pom.xml
Fix #1704 
Upgraded Fabric8 Kubernetes Client to v4.5.2 which caused
this issue
=> fix #1704: fabric8:build failing on openshift

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/PatchService.java
=> Fix #1696: f8 not setting imagestreams resourceVersion properly.

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
=> Fix #1689: HELM mode does not support parameters without value

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java
=> Fix #1710: Docker build args not working

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/ApplyService.java, core/src/main/java/io/fabric8/maven/core/service/kubernetes/JibBuildService.java
=> Fix #1696: Fix failures in PUT during applying ImageStreams

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/AbstractFabric8Mojo.java
=> Fix #1572: Support maven --batch-mode option

parent/pom.xml
Use image with fix
https://github.com/fabric8io-images/tomcat/pull/3
=> #1621: Use Docker image that doesn't require to run as specific user

.circleci/config.yml
This job would rebase branch with master first and then test
+ Added rebase and build job
+ Replaced `machine` builds with docker images
=> Added a job for rebase and test

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/FatJarDetector.java
=> Fix #1776: fat jar wrongly detected on simple jar
