fabric8io/fabric8-maven-plugin

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java, core/src/test/resources/fabric8/contains_kind.yml, core/src/test/resources/fabric8/contains_no_kind.yml
That's ok, when there is a kind included in the descriptor.
Fixes #35.
=> Allow 'typeless' names on the resource descriptors

plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java, sample/spring-boot/pom.xml
We need to extend the abstraction to allow a preEnriching() to build up default objects and a postEnriching() to customize after the label / annotation enricher has been called. Need to think about it, in order to make it not too complicated.
Fixes #72
=> Changed order between customizing via enricher and enriching labels.

plugin/src/main/java/io/fabric8/maven/plugin/docker/BuildMojo.java
fixes #78 so folks can choose to disable `fabric8:build` goal on  pom packaging projects
=> fixes #78 so folks can choose to disable `fabric8:build` goal on  pom packaging projects

enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherConfiguration.java, enricher/icon/src/main/java/io/fabric8/maven/enricher/icon/IconEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultImageEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultNameEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultReplicaSetEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultServiceEnricher.java
Instead of using String keys sprinkled around all over the code,
typesafe enum are used now. These are defined as inner classes in the
enricher, and provide an overview as well as type safety. Default
values are supported, too.
By accident it forces a certain naming convention. It could be that
this is to strict, but we can relax the constraints later, too.
=> Refactor enricher configuration.

customizer/spring-boot/src/main/java/io/fabric8/maven/customizer/spring/boot/SpringBootCustomizer.java
lets avoid using the image name docker property by default (we could maybe enable it with a setting later?)
=> lets avoid using the image name docker property by default (we could maybe enable it with a setting later?)

plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
fixes #77 to allow timestamp docker labels to be used for snapshot builds
=> fixes #77 to allow timestamp docker labels to be used for snapshot builds

generator/spring-boot/src/main/java/io/fabric8/maven/generator/springboot/SpringBootGenerator.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
This refers to an imagestream as created with fabric8:build -Dfabric8.build.mode=openshift
Had to switch back to `latest` tag for snapshots to make things simpler for the first shot.
=> . #12 - Add image change trigger to deployment configuration.

core/src/main/java/io/fabric8/maven/core/config/BuildRecreateMode.java, plugin/src/main/java/io/fabric8/maven/plugin/BuildMojo.java, release.groovy
* 'fabric8.build.mode' is now 'fabric8.mode' as it can be reused in other circumstances, too
* 'fabric8.recreate' is an enum for specifying what should be recreated.
=> Fixed issue with build mode and did some minor refavtorings

parent/pom.xml
@rhuss Need to get this in a release ASAP - currently broken against Kubernetes 1.3.3 & soon OpenShift too :)
=> Upgrade openshift-client to fix TLS issues

core/pom.xml, core/src/main/java/io/fabric8/maven/core/util/ClassUtil.java, core/src/test/java/io/fabric8/maven/core/util/ClassUtilTest.java, core/src/test/java/io/fabric8/maven/core/util/mainclass/one/sub/Bogus1.java, core/src/test/java/io/fabric8/maven/core/util/mainclass/one/sub/Bogus2.java, core/src/test/java/io/fabric8/maven/core/util/mainclass/one/sub/Bogus3.java, core/src/test/java/io/fabric8/maven/core/util/mainclass/one/sub/OneMain.java, core/src/test/java/io/fabric8/maven/core/util/mainclass/two/OneMain.java, core/src/test/java/io/fabric8/maven/core/util/mainclass/two/another/sub/a/bit/deeper/TwoMain.java, core/src/test/java/io/fabric8/maven/core/util/mainclass/zero/Bogus.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherConfig.java, generator/api/src/main/java/io/fabric8/maven/generator/api/BaseGenerator.java, generator/api/src/main/java/io/fabric8/maven/generator/api/GeneratorConfig.java, generator/api/src/main/java/io/fabric8/maven/generator/api/MavenGeneratorContext.java, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/generator/GeneratorManager.java, samples/spring-boot/pom.xml
This works currently for flat classpath apps. Only the classes in target/classes are examined.
I wonder whether certain lib jars should be examined, too.
=> . #146 : Add detection of a single MainClass

core/pom.xml, core/src/main/java/io/fabric8/maven/core/config/MetaDataConfig.java, core/src/main/java/io/fabric8/maven/core/util/Gofabric8Util.java, core/src/main/java/io/fabric8/maven/core/util/ProcessUtil.java, doc/src/main/asciidoc/inc/_access.adoc, doc/src/main/asciidoc/inc/_migration_2.adoc, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/AbstractInstallMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ClusterStopMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/InstallMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java, samples/spring-boot/pom.xml, samples/spring-boot/src/main/java/io/fabric8/maven/sample/spring/boot/HelloController.java
* Not yet done: Call of 'fabric8:install' in case there is now gofabric8 in the path. Currently the goal bails out.
* Requires 0.15-SNAPSHOT of d-m-p
* Also still open: `gofabric8 docker-env` asks for user + password if not connected, but this shouldnt be the case (an empty string should be printed). See  https://github.com/fabric8io/gofabric8/issues/175 for this issue.
=> . #333 - Initial implementation for using `gofabric8 docker-env` as a fallback.

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ImageEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, plugin/src/main/java/io/fabric8/maven/plugin/ResourceMojo.java
Heads up, this might be a breaking (but necessary) change: In order to not messe up resource objects like database which are part of an application but not the application itself and which does not e.g. an update of the image spec, **only descriptors with no name or with the artifact name of the project* are enriched with Enricher.addMissingResources() (i.e. only those are feed into the enrichers).
This fixes #359.
=> Only update app specific resource descriptors.

plugin/src/main/java/io/fabric8/maven/plugin/AbstractInstallMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/ClusterStartMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/InstallMojo.java
no need to run `gofabric8 install` as gofabric8 start does that anyway and avoids the double download or download of minikube when using minishift
=> lets improve cluste-start for #466 #465

plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/AbstractInstallMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/ClusterStartMojo.java
+ changed 'fabric8.vm.driver' to 'fabric8.cluster.driver'
=> Allow also `fabric8.mode` for selecting the cluster type

core/pom.xml, core/src/main/java/io/fabric8/maven/core/util/ResourceFileType.java, parent/pom.xml
This PR upgrade  com.fasterxml.jackson.dataformat:jackson-dataformat-yaml to version 2.8.4 which contains the bugfix https://github.com/FasterXML/jackson-dataformat-yaml/pull/78 for not unquoting strings which contain boolean values.
When 2.9 is out then this should be taken along with the then new feature LITERAL_BLOCK_STYLE (instead of MINIMIZE_QUOTES). See https://github.com/FasterXML/jackson-dataformat-yaml/pull/76 for details.
=> Add support for generation of multi-line YAML resources

enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java
Whenever the plugin is used in a project without main-class or anything that triggers a generator, an **invalid** deployment is created by default. I added a check to verify that at least an image is present in the configuration before generating the default config.
A simple use case: project defining only integration tests for other projects. A deployment should not be created for the project containing the test suite (https://issues.jboss.org/browse/OSFUSE-389).
=> OSFUSE-389: Avoid building invalid deployments

core/src/main/java/io/fabric8/maven/core/config/MetaDataConfig.java, doc/src/main/asciidoc/inc/_enricher.adoc, doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, plugin/src/main/java/io/fabric8/maven/plugin/enricher/MetadataEnricher.java
Migrated from using Map<String, String> to describe labels and annotations to using properties, which allow for labels or annotations containing characters that are not valid in XML syntax (like forward slashes).
I've also updated the documentation to reflect this. Also fixed a minor typo in the documentation.
=> Issue #617: Can't create annotations with a slash in the name

doc/src/main/asciidoc/inc/_generator.adoc, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/FatJarDetector.java, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, generator/spring-boot/src/main/java/io/fabric8/maven/generator/springboot/SpringBootGenerator.java
The spring-boot-generator now adds the spring devtool.jar directly to the fat-jar instead
of putting a cuckoo egg into target/classes. This also now works directly
when fabric8:build is called (so no need to rely that fabric8:resource kicked in earlier).
Added documentation to all generators with base images chosen and configuration options.
=> Add generator documentation, refactored spring-boot-generator

core/src/main/java/io/fabric8/maven/core/access/ClusterAccess.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/AbstractLiveEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/WatchMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/ImportMojo.java
Fix for the RH branch and then for master if it is approved.
Authentication mechanisms (eg. basic authentication) are handled differently in KubernetesClient and OpenshiftClient, but the plugin always create a KubernetesClient to execute mojo operations.
I centralized the creation of the client and now the correct instance is chosen according to the type of cluster or user preferences (`fabric8.mode`).
This will allow deploying applications from the eclipse tooling using a command like:
```
mvn clean fabric8:deploy -Dfabric8.namespace=myproject -Dkubernetes.master=https://$(minishift ip):8443 -Dkubernetes.auth.basic.username=admin -Dkubernetes.auth.basic.password=admin -Dkubernetes.auth.tryKubeConfig=false -Dkubernetes.trust.certificates=true -Dkubernetes.auth.tryServiceAccount=false
``` …
=> OSFUSE-435: allow using properties to configure access

enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java
As only the first port is added to default generated service, order of ports is import so have to use a list rather than a set.
=> Ports should be ordered in default service generator

core/src/main/java/io/fabric8/maven/core/access/ClusterAccess.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/AbstractLiveEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/WatchMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/ImportMojo.java
This merges the changes made on branch 'v3.1.80-redhat' (for authentication using properties) into master.
Tested on Minishift and origin 1.4.
=> OSFUSE-435: Allow using properties to authenticate against Openshift cluster

plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Configure to ignore fabric8-maven-plugin goals in Eclipse to avoid
errors when importing a project using fabric8-maven-plugin
=> #700: Default m2e configuration to avoid errors in Eclipse

core/src/main/java/io/fabric8/maven/core/util/PluginServiceFactory.java
This broke TreeSet and has overwritten any entries with the same order value
(as it was the case for the JavaExecGenerator and VertxGenerator).
Fixes #717
=> Fix compareTo so that is corresponds to equals()

plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/AbstractInstallMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/ImportMojo.java
When doing fabric8:cluster-start:
> [INFO] F8: Please add the following to your ~/.bashrc:
> [INFO] F8:   export PATH=$PATH:/home/comp_/.fabric8/bin
> Would you like to add the path setting to your ~/.bashrc now? (Y/n):
The capital "Y" suggests that is the default value but just hitting Return will be interpreted as "n". Same for "y" and "yes".
=> Handle default value and lowercase answers in maven prompts.

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java
When using this flag, the only precondition is now that only a single service is exposed.
Relates to https://issues.jboss.org/browse/OSFUSE-479
=> OSFUSE-479: Add route for fabric8.deploy.createExternalUrls for OpenShift hift regardless of Service Type

core/src/main/java/io/fabric8/maven/core/config/OpenShiftBuildStrategy.java, doc/src/main/asciidoc/inc/_generator.adoc, generator/api/src/main/java/io/fabric8/maven/generator/api/FromSelector.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/JavaRunGenerator.java, generator/api/src/main/resources-filtered/META-INF/fabric8/default-images.properties, generator/api/src/test/java/io/fabric8/maven/generator/api/FromSelectorTest.java, generator/api/src/test/java/io/fabric8/maven/generator/api/support/BaseGeneratorTest.java, generator/api/src/test/resources/META-INF/fabric8/default-images.properties, generator/karaf/src/main/java/io/fabric8/maven/generator/karaf/KarafGenerator.java, generator/karaf/src/main/resources-filtered/META-INF/fabric8/default-images.properties, generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/WebAppGenerator.java, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
If a configuration `fromMode == "istag"` is given for a generator, then an ImageStreamTag is used for the base image. This can be either given in the `from` config in the format "namespace/stream-name:tag" or a default image is used based on the generator (similar like for the plain docker case)
The deault imagestream tags are "openshift/fis-java-openshift:2.0" and "openshift/fis-karaf-openshift:2.0" for the repective generator.
The fromMode can also be set from the command line with '-Dfabric8.generator.fromMode=istag".
Open question is whether to make the "istag" mode the default when running under OpenShift. However since the ImageStreamTag must already exists, this can lead to errors (in the plain docker case it would be simply pulled from a registry). A more sophisticated default …
=> Support for ImageStreamTags in generators

enricher/api/src/main/java/io/fabric8/maven/enricher/api/AbstractHealthCheckEnricher.java, it/src/it/spring-boot/expected/kubernetes.yml, it/src/it/spring-boot/expected/openshift.yml
This fixes #776 "LivenessProbe is no longer enriched"
=> Fixes #776 livenessProbe in spring-boot-health-check enricher

core/src/main/java/io/fabric8/maven/core/openshift/OpenShiftBuildService.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, doc/src/main/asciidoc/inc/_generator.adoc, generator/api/src/main/java/io/fabric8/maven/generator/api/FromSelector.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java, generator/api/src/main/resources-filtered/META-INF/fabric8/default-images.properties, generator/api/src/test/java/io/fabric8/maven/generator/api/support/BaseGeneratorTest.java, generator/karaf/src/main/resources-filtered/META-INF/fabric8/default-images.properties, parent/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/AbstractTailLogMojo.java
Set `fromMode=="istag"` for `-redhat` plugins, if 
* build mode is "OpenShift"
* No `fromMode` is given directly
* Build strategy is "s2i"
The default imagestream tag is calle "fis-java-openshift" for `-redhat` and "fabric8-java" for upstream.
=> Osfuse 283 istag is default from mode for redhat

core/src/main/java/io/fabric8/maven/core/util/Constants.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AutoTLSEnricherTest.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/VolumePermissionEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/VolumePermissionEnricherTest.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
This will avoid running the VolumePermissionEnricher for OpenShift. However, the proper solution is to use an appropriate profile where this enricher is not included if you dont want to have this sort of enrichment (which is maybe still a hack ?)
Fixes #790
=> Partial fix for #790

it/src/it/simple/expected/openshift.yml, it/src/it/spring-boot/expected/openshift.yml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
It seems that this long timeout could cause issues to detect errors early in deployments e.g. when the pod fails to start. AFAIK it was introduced to compensate long pull times of images over slow internet connections.
However, since I consider this a rare use case compared to the normal usage (where an image can easily be downloaded in the 10 minute or so default), I wouls like to remove that as default. The timeout can always be set explicitly when coming into a very-slow network situation (where an upfront pull of images might make even more sense).
I open the discussion, whether a default of 3 hours should be used or not. Its **not** about the feature itself, which is quite useful (and which btw, if set, automatically uses a `RollingUpdate` deployment strategy, otherwise no deployment …
=> Removed default of 3 h for a DeploymentConfig on OpenShift

core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ImageEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/ImageEnricherTest.java, it/src/it/env-metadata/expected/kubernetes.yml, it/src/it/env-metadata/expected/openshift.yml, it/src/it/env-metadata/invoker.properties, it/src/it/env-metadata/pom.xml, it/src/it/env-metadata/src/main/java/zero/Application.java, it/src/it/env-metadata/src/main/java/zero/HelloController.java, it/src/it/env-metadata/verify.groovy, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
Added env variables to the container through the image enricher.
The order of the `fmp-image` enricher was wrong. It must run after the `fmp-controller` to be effective. The enricher simply did nothing because the Deployment/DC/RS/DS were not present in the builder.
I added an integration test to prevent this happening again.
=> Fixes #723: Add env variables to container

it/pom.xml, it/src/it/volume-enricher-storage-class-835/expected/openshift.yml, it/src/it/volume-enricher-storage-class-835/verify.groovy, it/src/test/java/io/fabric8/maven/it/Verify.java
This is related to #835 and #790. The tests should ensure these fixes.
Fixes #835
=> Ensure that no init-containers are created for OpenShift

watcher/standard/pom.xml
especially the dependency on hibernate validator is annoying as hibernate validator tends to be a beast w.r.t to logging
=> Get rid of (apparently) unused dependencies

enricher/fabric8/src/main/resources/META-INF/fabric8/enricher-default, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, generator/java-exec/src/main/resources/META-INF/fabric8/generator-default, generator/karaf/src/main/resources/META-INF/fabric8/generator-default, generator/spring-boot/src/main/resources/META-INF/fabric8/generator-default, generator/vertx/src/main/resources/META-INF/fabric8/generator-default, generator/webapp/src/main/resources/META-INF/fabric8/generator-default, generator/wildfly-swarm/src/main/resources/META-INF/fabric8/generator-default, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
Removed order ids from enricher/generator definitions since the order are defined in the profile used (which is defined in "profiles-default.yml".
Also added some comments to clarify stuff a bit.
=> Removed order ids from enricher/generator definitions

core/src/main/java/io/fabric8/maven/core/util/SpringBootProperties.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/SpringBootHealthCheckEnricher.java
Spring Boot apps with a non-empty context root (i.e. a value for "server.context-root" in application.properties) currently get a readiness and liveness check that points to the wrong path ("/health" rather than "/context-root/health"). This obviously means that Kubernetes will continually redeploy the pods because it thinks they are unhealthy. This PR fixes that. Not sure if there is a place for this in the documentation - it's really something that should "just work".
=> Awareness of Spring Boot context path to readiness and liveness checks

plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java
`.spec.selector` is optional for jobs. There is no need to generate it by default.
=> Do not generate a default selector for jobs

core/src/main/java/io/fabric8/maven/core/util/MavenUtil.java, it/src/it/env-metadata/expected/kubernetes.yml, it/src/it/env-metadata/expected/openshift.yml, it/src/it/simple-maven-issue-mgmt/expected/kubernetes.yml, it/src/it/simple-maven-issue-mgmt/expected/openshift.yml, it/src/it/simple-maven-scm/expected/kubernetes.yml, it/src/it/simple-maven-scm/expected/openshift.yml, it/src/it/simple/expected/kubernetes.yml, it/src/it/simple/expected/openshift.yml, it/src/it/spring-boot/expected/kubernetes.yml, it/src/it/spring-boot/expected/openshift.yml
#206 
https://github.com/kubernetes/kubernetes/issues/12463
https://github.com/kubernetes/kubernetes/pull/25041
https://github.com/kubernetes/kubernetes/pull/28005
=> increasing the service name length to 63 to reflect the updated limits in kubernetes v1.4.0

core/src/main/java/io/fabric8/maven/core/config/ProcessorConfig.java, core/src/main/java/io/fabric8/maven/core/config/Profile.java, core/src/main/java/io/fabric8/maven/core/util/ProfileUtil.java, core/src/test/java/io/fabric8/maven/core/config/ProfileTest.java, core/src/test/resources/fabric8/config/ProcessorConfigTest.yml, doc/src/main/asciidoc/inc/_enricher.adoc, doc/src/main/asciidoc/inc/_profiles.adoc, doc/src/main/asciidoc/inc/generator/_overview.adoc, samples/spring-boot/pom.xml
Revised the merging part of profiles and configuration.
Now, when a generator is specified in <configuration> it is moved to the *beginning* of the list of generators, which makes sense since normally the first genertor kicking wins.
For enricher it's not so clear, but now enrichers are also moved to the beginning to the enricher list for consistencies sake.
For fined tuned enricher/generator ordering handling it is recommend to use an explicit (possibly handcrafted) profile where the order can be fine tuned.
Fixes #862
=> Fixed order of generators when merging configs and profiles

core/src/main/java/io/fabric8/maven/core/service/BuildService.java, core/src/main/java/io/fabric8/maven/core/service/kubernetes/DockerBuildService.java, core/src/main/java/io/fabric8/maven/core/service/openshift/ImageStreamService.java, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, core/src/test/java/io/fabric8/maven/core/service/openshift/ImageStreamServiceTest.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, samples/spring-boot/pom.xml
These are added to a Maven repository on deploy. Please note that this file makes only sense in the context of an OpenShift cluster where the image has been build.
First step in fixing and solving #910
=> Add runtime file with imagestreams as artefacts with classified '-is'

core/src/main/java/io/fabric8/maven/core/config/ServiceConfig.java, core/src/main/java/io/fabric8/maven/core/handler/ServiceHandler.java, doc/src/main/asciidoc/inc/_enricher.adoc, doc/src/main/asciidoc/inc/_installation.adoc, doc/src/main/asciidoc/inc/enricher/_fmp_service.adoc, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricherTest.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java, it/src/it/docker-health-checks/invoker.properties
* `port` can now take a comma separated list with explicit mappings
* `multiPort` can be switched on to allow multi-port services
* Worked on documentation
* Got rid of ServiceConfig and ServiceHandler which also decouples the enricher from the XML configuration classes.
* Made logic (hopefully) easier to understand
Still todo: Verify and document the way how the enrichment of an existing service works.
Fixes #921
=> Refactor and enhanced Enricher 'fmp-service'

core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricherTest.java
allow maven projects to specify replicas count via <resources> like
```
<plugin>
<groupId>io.fabric8</groupId>
<artifactId>fabric8-maven-plugin</artifactId>
<version>${fabric8-maven-plugin.version}</version>
<executions>
<execution>
<id>fmp</id>
<goals>
<goal>resource</goal>
<goal>helm</goal>
<goal>build</goal>
</goals>
</execution>
</executions>
<configuration>
<resources>
<replicas>3</replicas>
</resources>
</configuration>
</plugin>
```
=> Allowing replicas to be set to the fmp-controller

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
that's for a RollingUpdate and intended to compensate long image download times on slow networks.
Please follow the discussion on https://github.com/fabric8io/fabric8-maven-plugin/pull/944#discussion_r116962969 for more about this default values.
Is related to #944 and supersedes it.
=> Increase deployment config timeout to 3600s

doc/src/main/asciidoc/inc/_introduction.adoc
labels must be inside `<all>` these days
=> fix typo in docs

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/main/java/io/fabric8/maven/core/util/ResourceVersioning.java, core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, it/src/it/deployment-strategy-type-919/expected/openshift.yml, it/src/it/deployment-strategy-type-919/pom.xml, it/src/it/raw-resources/pom.xml, it/src/it/simple-maven-issue-mgmt/pom.xml, it/src/it/simple-maven-scm/pom.xml, it/src/it/simple/pom.xml, it/src/it/spring-boot/pom.xml, it/src/it/statefulset/expected/kubernetes.yml, it/src/it/statefulset/expected/openshift.yml, it/src/it/statefulset/invoker.properties, it/src/it/statefulset/pom.xml, it/src/it/statefulset/src/main/fabric8/statefulset.yml, it/src/it/statefulset/src/main/java/io/fabric8/maven/sample/spring/boot/Application.java, it/src/it/statefulset/verify.groovy, it/src/it/volume-enricher-custom-storage-class/pom.xml, it/src/it/volume-enricher-storage-class-835/pom.xml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
This adds support for fragments in StatefulSets. Requires newer (unreleased) version of kubernetes-api to work (or equivalent Controller after #949). Added `it` test.
=> Improvements for StatefulSet

core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, doc/src/main/asciidoc/inc/goals/develop/_fabric8-watch.adoc, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/WatchEnricher.java, enricher/fabric8/src/main/resources/META-INF/fabric8/enricher-default, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
Waiting for feedback for the problem that forces undeploy, this is a proposal for fixing the date parsing problem (we can also wait for a new release of fabric8, but it's a simple method) and generating resources with only one replica through a specific enricher for the watch task.
(I wasn't able not to use the goal finder... sorry :D)
=> Fixes the watch task #928

core/src/test/resources/fabric8/named-svc.yaml, core/src/test/resources/fabric8/svc.yml, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ProjectEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/MavenProjectEnricherTest.java, it/src/it/deployment-strategy-type-919/expected/openshift.yml, it/src/it/deployment-strategy-type-919/src/main/fabric8/fabric8-docker-registry-deployment.yml, it/src/it/env-metadata/expected/kubernetes.yml, it/src/it/env-metadata/expected/openshift.yml, it/src/it/raw-resources/expected/kubernetes.yml, it/src/it/raw-resources/expected/openshift.yml, it/src/it/raw-resources/src/main/fabric8/raw/sample-svc.yml, it/src/it/simple-maven-issue-mgmt/expected/kubernetes.yml, it/src/it/simple-maven-issue-mgmt/expected/openshift.yml, it/src/it/simple-maven-scm/expected/kubernetes.yml, it/src/it/simple-maven-scm/expected/openshift.yml, it/src/it/simple/expected/kubernetes.yml, it/src/it/simple/expected/openshift.yml, it/src/it/spring-boot/expected/kubernetes.yml, it/src/it/spring-boot/expected/openshift.yml, it/src/it/statefulset/expected/kubernetes.yml, it/src/it/statefulset/expected/openshift.yml, it/src/it/volume-enricher-custom-storage-class/src/main/fabric8/fabric8-docker-registry-deployment.yml, it/src/it/volume-enricher-custom-storage-class/src/main/fabric8/fabric8-docker-registry-svc.yml, it/src/it/volume-enricher-storage-class-835/src/main/fabric8/fabric8-docker-registry-deployment.yml, it/src/it/volume-enricher-storage-class-835/src/main/fabric8/fabric8-docker-registry-svc.yml
I've changed the resource generation to use the `app` label instead of `project`. I've added a switch to use the previous version (and documented it). Fixed all tests.
This makes the deployed artifacts more "standard" on Opensfhit (#945).
@jstrachan, @rhuss , do you know any other part of fabric8 that may be affected by this change?
=> Fixes #945: Use the app label instead of project

core/pom.xml, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/main/java/io/fabric8/maven/core/util/OpenShiftOverrideResources.java, core/src/test/java/io/fabric8/maven/core/util/MergeResourceTest.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/MergeEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
lets users specify partial YAML files to override data in YAML manifests placed in the `src/main/fabric8-openshift` folder
which override the resources inside `src/main/fabric8` when generating the openshift specific YAML
e.g. this lets you override annotations, labels or environment variables for openshift specific settings
fixes #983
=> provide an openshift override folder

core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java, doc/src/main/asciidoc/inc/generator/_options_common.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ImageEnricher.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java, generator/api/src/test/java/io/fabric8/maven/generator/api/support/BaseGeneratorTest.java, generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java, it/src/it/registry-286/expected/kubernetes.yml, it/src/it/registry-286/expected/openshift.yml, it/src/it/registry-286/invoker.properties, it/src/it/registry-286/pom.xml, it/src/it/registry-286/src/main/java/io/fabric8/maven/sample/spring/boot/Application.java, it/src/it/registry-286/verify.groovy, parent/pom.xml
I think this should be sufficient to use a registry in the docker image. The image can be tagged using the full name (with the registry) and used also in local mode as is, so the registry can be provided as command line option or configured in the pom.xml without issues.
@rhuss, can you give a quick look?
=> Fix #286 by adding a registry option

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
lets only replace an openshift specific dependent resource if the current resource is not already an openshift specific resource. i.e. so we can override openshift specific resources from dependents
=> fixes #1055

CHANGELOG.md, doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Fabric8-maven-plugin should always use DeploymentConfigs if using ImageStreams; but if not we should probably default to Deployments.
=> Fixes #1042 Switch to using Deployments rather than DeploymentConfig on OpenShift when not using ImageStreams

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/DebugConstants.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, doc/src/main/asciidoc/inc/goals/develop/_fabric8-debug.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java
This requires the base image to support the env variable `JAVA_DEBUG_SUSPEND` (https://github.com/fabric8io-images/run-java-sh/pull/21 and other PRs to come for the base images).
Each run of `fabric8:deploy -Dfabric8.debug.suspend` restarts the pod, so a debugger can attach at startup. Readiness probes are disabled.
=> Fixes #1003: adding fabric8.debug.suspend flag

doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
Instead, try to detect the default by checking whether there has been
some image configurations with build sections resolved.
This can always overwritten by explicitly specifying fabric8.skip.build.pom
=> feature: Don't use a default for skipBuildPom

rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxConfigmapBoosterIT.java
A recent change in vertx-configmap-booster project has caused the build
process to automatically create resources during build(see src/main/fabric8
in that project). So it's better to edit configmap after build process.
For more details, see https://github.com/openshiftio-vertx-boosters/vertx-configmap-booster/commit/2afa3e1a66e8e895d9a6dc91d94880480a478f28
=> Fix VertxConfigmapBooster test

CHANGELOG.md, doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentConfigOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/KubernetesToOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/NamespaceOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/ReplicSetOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
+ Added a workaround to deal with ImageTriggers.
+ Added flag fabric8.openshift.trimImageInContainerSpec which would trim
image in container spec
#1130
=> Fixes #1130 Application redeployment is getting failed on OpenShift v3.7.0

doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentConfigOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/KubernetesToOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/NamespaceOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/converter/ReplicSetOpenShiftConverter.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Fixes #1130 Application redeployment is getting failed on OpenShift v3.7.0
+ Added a workaround to deal with ImageTriggers.
+ Added flag fabric8.openshift.trimImageInContainerSpec which would trim
image in container spec
+ Updated documentation related to flag.
Backporting changes to accomodate:
OSFUSE-718: [OSO][OCP 3.7] f-m-p redeployments failing to deploy
=> PATCH-2506: [OSFUSE-718] [OSO][OCP 3.7] f-m-p redeployments failing to deploy

doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
=> fix: revert skipBuildPom default to always true for 'pom' packaging.

rt/pom.xml, rt/src/test/java/io/fabric8/maven/rt/SpringbootHttpBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxHealthchecksBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxHttpBoosterIT.java
**Changes Proposed**
* Renamed `VertxHealthchecksBooster` to `VertxHealthchecksBoosterIT` to catch it for failsafe plugin
* Removed unnecessary `testng` dependency, adds `junit` for it.
* Adds test scope for all dependency from `rt/pom.xml`
=> fix: use correct dependency of junit

Jenkinsfile, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/DependencyEnricherTest.java
This will fix the issue of `to run test before generating tags` during release
#1195
=> Now release will first build and test before generating tags

CHANGELOG.md, generator/wildfly-swarm/src/main/java/io/fabric8/maven/generator/wildflyswarm/WildFlySwarmGenerator.java
The Jolokia agent, which used to have problems with WildFly Swarm due to
how Java LogManager is set, works fine since Jolokia 1.3.6. This means that
the Fabric8 Java S2I image has been OK since version 2.0. Hence I believe
it is safe to re-enable Jolokia for WildFly Swarm applications now.
At the same time, the Fabric8 Java S2I image version 2.1 added a Prometheus
agent, which suffers from the same problem. Hence I believe it should be
disabled for WildFly Swarm applications (for now).
=> disable Prometheus and re-enable Jolokia for WildFly Swarm

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/Configs.java, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/SpringBootHealthCheckEnricher.java, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AbstractSpringBootHealthCheckEnricherSupport.java
We ran into a problem in our Kubernetes deployment: when many microservices are started at the same time, they take longer to initialize. After the initial delay, Kubernetes kills the services because they started too slowly, and tries again.
By setting a custom initial delay, we can avoid this situation. Here is the required configuration change.
```
<plugin>
<groupId>io.fabric8</groupId>
<artifactId>fabric8-maven-plugin</artifactId>
<version>${fabric8.maven.plugin.version}</version>
<configuration>
<enricher>
<config>
<spring-boot-health-check>
<readiness-initial-delay>20</readiness-initial-delay>
<liveness-initial-delay>360</liveness-initial-delay>
</spring-boot-health-check>
</config>
</enricher>
</configuration>
</plugin>
```
If I understand correctly, the two changes in this PR will …
=> SpringBootHealthCheckerEnricher - change initial delay for liveness and readiness checks via configuration properties

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
With this change the plugin will not try to install into maven repository the yml imagstream if not generated.
#1247
=> Fix 1247: do not try to install non-existent imagestream yml file

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java
Fix the yaml error which is producing an invalid yaml when using the flag `fabric8.openshift.trimImageInContainerSpec=true`
#1237
=> Fix the yaml error which is producing a invalid yaml

CHANGELOG.md, rt/src/test/java/io/fabric8/maven/rt/BaseBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/BoosterYaml.java, rt/src/test/java/io/fabric8/maven/rt/Environment.java, rt/src/test/java/io/fabric8/maven/rt/EnvironmentType.java, rt/src/test/java/io/fabric8/maven/rt/GitSource.java, rt/src/test/java/io/fabric8/maven/rt/ReadYaml.java, rt/src/test/java/io/fabric8/maven/rt/Source.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootCrudBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/SpringbootHttpBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxConfigmapBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxHealthchecksBoosterIT.java, rt/src/test/java/io/fabric8/maven/rt/VertxHttpBoosterIT.java
Fixed use a released version of all the Boosters
in place of always using master.
This will also help in regression tests breaking regularly
#1245
=> Fixes use released version of boosters in FMP regression tests

generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java
Fixes #1282
If the system running maven has a restrictive umask the generated fatjar may
not be executable inside the container.
Signed-off-by: Thomas Weißschuh <thomas.weissschuh@de.amadeus.com>
=> [java-exec] set permissions on fatjar

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java
Better getting this fix before upgrading kubernetes client in f-m-p: https://github.com/fabric8io/kubernetes-client/pull/1074#pullrequestreview-119001818
However, this fix is for handling better watcher edge cases and avoid npe when we can just print a warning.
=> Fix #1263: handle better watcher edge cases

core/pom.xml, enricher/api/pom.xml, parent/pom.xml, rt/pom.xml
Updated Kubernetes Client Dependency Version and also right now it is using from
Kubernetes-api so fixed that so that it will always use the mentioned client and model
=> Updated Kubernetes Client Dependency

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java
#1133
+ Reverted my previous fix which was intended to suppress this
+ Now log additional things in case we get SocketTimeoutException; like querying
BuildConfig and checking DockerImage/ImageStreamTags
Related OSIO issue: https://github.com/openshiftio/openshift.io/issues/3058
=> Fix #1133 : Handle intermittent SocketTimeoutException while s2i build

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/BuildService.java, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java, doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
Fabric8:build goal fails to pull base image from private registry with authentication.
Buildconfig created for the didn't use to create/assign pullSecret for it to pull image from a private registry when run in Openshift mode unlike Kubernetes mode which would pick up values such as docker.registry, its credentials etc. from maven settings.xml.
The changes in this PR, adds below:
1. Create a pullSecret by using default values for private registry (docker.registry, server credentials from settings.xml) if present. Update it if already present & if any changes.
2. Assign this pullSecret to buildConfig when running fabric8:build goal.
The name of pullSecret that will be created can be controlled by maven param: "fabric8.build.pullSecret" (Default: pullsecret-fabric8).
Addresses #1293
=> Create pullSecret in buildConfig when pulling from private registry in Openshift.

CHANGELOG.md, doc/src/main/asciidoc/inc/generator/_webapp.adoc, generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/WebAppGenerator.java, generator/webapp/src/main/resources/assemblies/webapp.xml, parent/pom.xml, samples/webapp/pom.xml
and also fix the assembly to include the proper artefact, regardless
of the 'final' name.
Fixes #1276.
=> feature: Add "path" to webapp generator

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java, core/src/test/java/io/fabric8/maven/core/handler/ContainerHandlerTest.java
In this Pull request the registry-handling is implemented according to the documentation: https://maven.fabric8.io/#registry
I discovered that for the `fabric8:resource` step, the `docker.pull.registry` is ignored. So here is the fix.
Signed-off-by: Michael Sprauer <Michael.Sprauer@sap.com>
=> support for docker.pull.registry

CHANGELOG.md, parent/pom.xml
Fixes #1268 as this base images contains fix for re-enabling the OpenShift Java Console
=> fix(base-images): Update to s2i 2.2

doc/src/main/asciidoc/inc/generator/_spring_boot.adoc
Add more details info related to liveness and readiness probes HTTPS as this info is not clear for docs readers and can be detected in source code only.
=> Add more details info related to liveness and readiness probes HTTPS

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java
=> Fix #1312 : Container name should not be generated from maven group Id

CHANGELOG.md, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/SpringBootHealthCheckEnricher.java, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AbstractSpringBootHealthCheckEnricherSupport.java
In attempting to configure the health check timeout for our Spring Boot app, we did not find a configuration option that allows us to do it. This modification allows a user to configure the timeout.
=> Allow configurable timeoutSeconds for SpringBootHealthCheckEnricher

CHANGELOG.md, Jenkinsfile, README.md
+ Not sure if these downstream dependencies like fabric8-tenant-che, fabric8-tenant-jenkins,
fabric8-devops are still active or not. So dropping their updated in order to
smoothen release flow.
+ Updated CHANGELOG.md according to next release
=> Minor Changes in Jenkinsfile to avoid updating downstream dependencies

CHANGELOG.md, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/IconEnricher.java, generator/karaf/src/main/java/io/fabric8/maven/generator/karaf/KarafGenerator.java
Not touching the others, but Karaf has repackaged versions of the plugin, so the detection should be flexible. I've also fixed the detection of the spring-boot maven plugin in the icon enricher.
=> Support repackaged maven plugins for Karaf

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/ApplyService.java, core/src/main/java/io/fabric8/maven/core/service/PatchService.java, core/src/main/java/io/fabric8/maven/core/util/kubernetes/UserConfigurationCompare.java, core/src/test/java/io/fabric8/maven/core/service/openshift/PatchServiceTest.java, parent/pom.xml
#894 
+ Whenever we detect that a resource with a certain name exists, edit()
instead of doing replace()
=> Fix #894: Service with NodePort always gets a new port after 'fabric8:apply'

.gitignore, CHANGELOG.md, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/ServiceDiscoveryEnricher.java, enricher/fabric8/src/main/resources/META-INF/fabric8/enricher-default, enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/ServiceDiscoveryEnricherTest.java, enricher/fabric8/src/test/resources/spring/camel-context.xml, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
Initially just for Camel Rest DSL Projects. Support for other types of projects will follow later.
See also: https://issues.jboss.org/browse/ENTESB-9252
=> feat: Adding Service Annotations for Service Discovery

core/src/main/java/io/fabric8/maven/core/model/GroupArtifactVersion.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/NameEnricher.java
Fix #918: Adds Sanitize method to generate valid Kubernetes resources names
=> fix(#918): Adds Sanitize method to generate valid Kubernetes resources

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Only run ConfigMapEnricher when ConfigMapEntries are present in pom
=> Fix #977 regression: Don't add ConfigMapEnricher to default profile

CHANGELOG.md, parent/pom.xml, samples/xml-config/pom.xml
Fix #1386 
+ Update dmp to 0.28.0 (which fixes this)
+ Changed a sample to pull dia sha digest
=> Fix #1386: Allow @sha256 digest for tags in FROM

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricherTest.java
Fixes #222 The SeviceEnricher could check the Docker image configuration for specific labels
(e.g. fabric8.service.myservice=9090) so that it could use this in a service's port
specification. The last part of the label should be the service name.
=> Fix #222 : ServiceEnricher should evaluate Image labels for ports

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/PushMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DeployMojo.java
=> Added 'skip' options to goals.

plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Omits this LoC that I added by mistake https://github.com/dev-gaur/fabric8-maven-plugin/blob/14cce77bd2464bce16ec841df4cf9864168ebdff/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java#L754
=> Omits the unnecessary repition of 'enricherManager.enrich(..)'

CHANGELOG.md, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/FileDataSecretEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/FileDataSecretEnricherTest.java, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
Similar to fmp-configmap-file enricher for annotation
Signed-off-by: bohmber <bommel@apache.org>
=> Allows user to define Secret from annotation

.circleci/config.yml, CHANGELOG.md, scripts/setup_openshift_environment.sh
This just reintroduces regression tests in our PR checks suite, Regression tests would stay as a separate repository but would be used only in a workflow. I have created a branch of https://github.com/rohanKanojia/fabric8-maven-plugin-rt which runs only one test which is sufficient enough to check build and deployment aspects. 
I'm suggesting to have these since current integration tests don't check build and deploy goals.
=> Proposal: Run e2e tests in circleci

.circleci/config.yml
=> Stop using 'sonar.analysis.mode' parameter as it is no more supported

it/src/it/simple-with-route-flag-false/expected/kubernetes.yml, it/src/it/simple-with-route-flag-false/expected/openshift.yml, it/src/it/simple-with-route-flag-true/expected/kubernetes.yml, it/src/it/simple-with-route-flag-true/expected/openshift.yml, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
We were getting weird behavior with itests when run with mini-shift running locally.
Even if the user passed -Dfabric8.mode as a parameter while running goals, they were
getting ignored and the cluster was getting queried always for mode.
=> Fixed my mistake, add runtimemode while resolving runtime mode in resourcemojo

CHANGELOG.md, doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/AbstractHealthCheckEnricher.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/SpringBootHealthCheckEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Fix #1444 
+ Added an option `fabric8.disableHealthChecks` to disable readiness/liveness checks
+ Added path option in SpringBootHealthCheckEnricher to overwrite path for liveness/readiness
=> Fix #1444: Option to Disable Liveness/readiness checks

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/handler/DeploymentConfigHandler.java, doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/AbstractHealthCheckEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/ImageChangeTriggerEnricher.java, enricher/standard/src/main/resources/META-INF/fabric8/enricher-default, plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
Fix #1037
I think I missed this while initial sidecar implementation. I misunderstood this as triggers getting added in Kubernetes case also. But it meant adding triggers only to main application container(which is done via reading the EnricherContext). Now it only adds triggers to the main application container. After this sidecars would work on Openshift also.
=> Fix #1037: Do not add ImageChange change triggers for Docker images

parent/pom.xml
This version was getting picked in our docs: http://maven.fabric8.io/
=> Chore: Update fmp version which is picked in docs

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/handler/HandlerHub.java
Refactoring HandlerHub
Fixes #1587
=> #issue1587

enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultNamespaceEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java
in #1609 I forgot to deal with use case when namespace is generated via yaml fragment. In this case, the other  generated resources should be generated with respective namespace annotation as well, which is not the case, currently.
```
namespace.yml
metadata:
name: fragment-ns
---------------------------------------
deployment.yml
metadata:
namespace: fragment-ns
```
Also, the apply goal wasn't working as expected.
=> Enable namespace metadata annotation when generating resource via fragments

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/access/ClusterConfiguration.java
=> Fix #1616: Goals failing with Access Configuration

enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/ImageChangeTriggerEnricher.java
Fix #1613 
This paramter was introduced in https://github.com/fabric8io/fabric8-maven-plugin/pull/1176 which stops
automatic redeployments in openshift by setting image field in DC empty.
I skipped this parameter during refactoring but now since it's causing redeployments on Openshift even
after setting fabric8.openshift.enableAutomatic=true; let's reintroduce this.
@mojsha ^^
=> Fix #1613: Re-introduce the fabric8.openshift.trimImageInContainerSpec parameter to set image field empty

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, core/src/main/java/io/fabric8/maven/core/service/ApplyService.java, core/src/main/java/io/fabric8/maven/core/service/PatchService.java, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesClientUtil.java, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ApplyMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/UndeployMojo.java
Fix #1591 
This PR allows fabric8 maven plugin to handle custom resource fragments. You can now create custom resources via providing custom resource yaml in `src/main/fabric8` directory. In order to create a custom resource you need to add it to your src/main/fabric8 directory like:
```
~/work/repos/fabric8-maven-plugin-sample-with-crd : $ ls src/main/fabric8/
animals.jungle.example.com-cr.yml  crd.yml  deployment.yml  raw  service.yml
```
Custom resources should be suffixed via **-cr.yml and Custom Resource Definition shall be suffixed via **-crd.yml . Apart from that we need to declare our custom resources definitions in fabric8-maven-plugin's XML config. For example, for a custom resource definition like :
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition …
```
=> Fix #1591: Adding Custom Resource support in Fabric8 Maven Plugin.

CHANGELOG.md, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ControllerViaPluginConfigurationEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java, samples/spring-boot-with-yaml/pom.xml
=> fixing issue 1632

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/ConfigMap.java, doc/src/main/asciidoc/inc/_enricher.adoc, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ConfigMapEnricher.java, it/src/it/configmap/expected/kubernetes.yml, it/src/it/configmap/expected/openshift.yml, it/src/it/configmap/pom.xml
=> Added support to choose configMap name

CHANGELOG.md, doc/ci-docs.sh, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java
=> fixing #issue872

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ControllerViaPluginConfigurationEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/ImageChangeTriggerEnricher.java, it/src/it/sidecar/invoker.properties, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
After discussion with @mojsha about the problems he is facing, I'm removing this parameter from Enricher config and adding it like a mojo parameter. Somehow maven doesn't recognize it when parameter contains "-" in the name.
=> Chore: Remove enrichAll flag from ImageChangeTriggerEnricher config

core/pom.xml, doc/pom.xml, enricher/api/pom.xml, enricher/deprecated/pom.xml, enricher/fabric8/pom.xml, enricher/standard/pom.xml, generator/api/pom.xml, generator/java-exec/pom.xml, generator/karaf/pom.xml, generator/quarkus/pom.xml, generator/spring-boot/pom.xml, generator/thorntail-v2/pom.xml, generator/vertx/pom.xml, generator/webapp/pom.xml, generator/wildfly-swarm/pom.xml, it/pom.xml, parent/pom.xml, plugin/pom.xml, pom.xml, samples/custom-enricher/secret-enricher/pom.xml, samples/peng/pom.xml, samples/quarkus/pom.xml, samples/thorntail/pom.xml, samples/xml-config/pom.xml, watcher/api/pom.xml, watcher/standard/pom.xml
Github considers first module in any multi module project's "Used By"
section. These are sorted alphabetically.
=> Chore: Fix Used by count on github

doc/src/main/asciidoc/inc/_compatibility.adoc
The compatibility tables for Kubernetes and Openshift were updated in accordance to the README.md file.
This fixes issue Docs: Compatibility with OpenShift and Kubernetes" section outdated Fixes #1664
=> Updated compatibility tables

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/ResourceUtil.java
Fixes #1714 
Modified Jackson ObjectMapper to disable minimizing quotes in case of yamls
=> Fix #1714: mvn fabric8:resource converts types of kubernetes YAML annotations in fragment

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/AutoTLSEnricher.java
Seems like we missed this during enricher refactoring, added the code
for adding service.alpha.openshift.io/serving-cert-secret-name annotation
Thanks to @mojsha for noticing this!
=> Fix AutoTLSEnricher for Service Serving Certificate Secrets

CHANGELOG.md, enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/RouteEnricher.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Fix #1720 
Removed the filtering of route from ResourceMojo. Ideally it should go into RouteEnricher
=> Fix #1720: Should be able to add custom route from YAML fragment, even if fabric8.openshift.generateRoute=false

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/ApplyService.java
=> Fix #1715: ApplyService#applyProjectRequest should be (truly) idempotent

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/ResourceUtil.java, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java, core/src/test/resources/fabric8/invalid-config-svc.yaml, it/src/it/env-yaml-boolean/expected/kubernetes.yml, it/src/it/env-yaml-boolean/expected/openshift.yml, it/src/it/env-yaml-boolean/invoker.properties, it/src/it/env-yaml-boolean/pom.xml, it/src/it/env-yaml-boolean/src/main/fabric8/deployment.yml, it/src/it/env-yaml-boolean/verify.groovy, parent/pom.xml
https://github.com/fabric8io/fabric8-maven-plugin/pull/1716 made the generated YAML files a lot less readable, but fixed #1714. I did some investigation, and it seems like our issue is caused by a bug in Jackson. The bug was still present in version 2.9.10, but fixed in 2.10.0.
This PR contains the following:
1. Revert the temporary fix for #1714 prepared by @rohanKanojia.
1. Introduce Jackson BOM to get dependency management on Jackson dependencies
1. Upgrade Jackson to the latest release (2.10.0)
1. Add dependency management for snakeyaml. Jackson requires a newer version than the default managed version by Maven (because of docker-maven-plugin).
There are several ways to fix the last issue/change. Please advice if you want me to do something else. I.e. exclude the transitive dependency …
=> Upgrade to latest version of Jackson (2.10.0). Better fix for #1714

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, samples/spring-boot-with-yaml/src/main/fabric8/deployment.yml, samples/spring-boot-with-yaml/src/main/fabric8/template.yaml
=> #1732 - Resolving template placeholders only in kubernetes.yaml but not individual template files (which will be resolved by helm mojo)

core/src/main/java/io/fabric8/maven/core/service/kubernetes/JibBuildService.java, core/src/main/java/io/fabric8/maven/core/util/JibBuildServiceUtil.java, core/src/test/java/io/fabric8/maven/core/service/kubernetes/JibBuildServiceTest.java
This is the simplest fix I could come up with now. My time to spend on this is sadly limited at the moment, but I think a lot should be improved with the Jib feature in f-m-p.
=> Fix #1737: Correct output directory for multi-module Maven build

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/kubernetes/JibBuildService.java, core/src/main/java/io/fabric8/maven/core/util/JibBuildServiceUtil.java, core/src/test/java/io/fabric8/maven/core/service/kubernetes/JibBuildServiceTest.java, generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java
=> Fix #1738: JibBuildConfiguration ignores BuildImageConfiguration.registry

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/YamlUtil.java, core/src/test/java/io/fabric8/maven/core/util/SpringBootUtilTest.java, core/src/test/resources/util/test-application.yml
Fix for https://github.com/fabric8io/fabric8-maven-plugin/issues/1695
=> Support integer keys in application.yaml

CHANGELOG.md, generator/quarkus/pom.xml, generator/quarkus/src/main/java/io/fabric8/maven/generator/quarkus/QuarkusGenerator.java, generator/quarkus/src/test/java/io/fabric8/maven/generator/quarkus/QuarkusGeneratorTest.java
Allow specifying in the configuration for the Quarkus generator the base image of the container. 
This change extracts the configured key `from` for the generator or reads the property `fabric8.generator.from` to use it as a base image for the container.
It also fallbacks to the default values in case any is provided.
=> QuarkusGenerator: Extract base image from config or fallback to default.

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/util/SpringBootUtil.java, core/src/main/java/io/fabric8/maven/core/util/YamlUtil.java, core/src/test/java/io/fabric8/maven/core/util/SpringBootUtilTest.java, core/src/test/resources/util/test-application-with-multiple-profiles.yml, generator/spring-boot/src/main/java/io/fabric8/maven/generator/springboot/SpringBootGenerator.java
Fix #797 
Tested on this simple sample https://github.com/r0haaaan/fmp-sample-with-multiprofile-spring-
By default it would assume the first profile specified in `applications.yml`. In order to override this behavior, `spring.profiles.active` property needs to be set.
=> Fix #797: spring-boot generator can not handle multi-profile configration

doc/src/main/asciidoc/inc/enricher/_fmp_service.adoc
`legacyPortMapping` doesn't exist anymore.
=> Doc omission for legacyPortMapping property

CHANGELOG.md, enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java, enricher/api/src/main/java/io/fabric8/maven/enricher/api/MavenEnricherContext.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ConfigMapEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/FileDataSecretEnricher.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/ConfigMapEnricherTest.java, enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/FileDataSecretEnricherTest.java
I am having issues using the ConfigMapEnricher in multi-module Maven projects. The enricher resolves files added to ConfigMap relative to the **working directory**, and not the **project directory**. This PR fixes this issue.
=> Fix: Enrichers should resolve relative paths against project directory, not working directory

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/OpenshiftBuildConfig.java, core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java, core/src/main/java/io/fabric8/maven/core/service/BuildService.java, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java, core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java, doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
Fix #1770 
This PR provides the support of configuring BuildConfig's spec using xml config or as a resource fragment. You can have xml config like this:
```
<plugin>
<groupId>io.fabric8</groupId>
<artifactId>fabric8-maven-plugin</artifactId>
<version>4.4-SNAPSHOT</version>
<configuration>
<resources>
<openshiftBuildConfig>
<limits>
<cpu>100m</cpu>
<memory>256Mi</memory>
</limits>
</openshiftBuildConfig>
</resources>
</configuration>
</plugin>
```
=> Fix #1770: Provide support for setting BuildConfig memory/CPU requests and limits

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
=> Display exception cause if possible

CHANGELOG.md, scripts/extract-changelog-for-version.sh
Simple script to extract changelog excerpts for a specific version and create GitHub compatible links.
Usage:
```
./scripts/extract-changelog-for-version.sh 4.4.0 5
```
Outputs:
```
- Fix #1572: Support maven --batch-mode option [5]
- Feature #1748: Quarkus generator: Extract base image from configuration. [6]
- Fix #1695: IllegalArgumentException when Spring Boot application.yaml contains integer keys [7]
- Fix #797: spring-boot generator can not handle multi-profile configuration [8]
- Fix #1751: Build Names are suffixed with -s2i regardless of build strategy [9]
- Fix #1770: Support for setting BuildConfig memory/cpu request and limits [10]
- Fix #1755: Spring boot enricher does not produce a proper heath check and liveness check path when "/" is used. [11]
- Feature: Check …
```
=> ci: Script to extract changelog portions and build links for notifications

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/config/OpenshiftBuildConfig.java, core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java, core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java
Fix #1770 
I accidentally added them for testing and forgot to retest it :-( . I apologize for
inconvenience caused. Thanks to @jflefebvre06 for spotting this.
I have tested it now and it seems to be working. 
```
~/work/repos/fmp-demo-project : $ cat pom.xml 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>meetup</groupId>
<artifactId>random-generator</artifactId>
<version>0.0.1</version>
<packaging>jar</packaging>
<name>random-generator</name>
<description>Demo project for Spring Boot</description>
<parent>
<groupId>org.springframework.boot</groupId> …
```
=> Fix #1770: Fixed my mistake, remove constructor from OpenshiftBuildConfig

CHANGELOG.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/FileDataSecretEnricher.java, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/SecretEnricher.java
=> Fix #1791: Added NullCheck in FileDataSecretEnricher

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/kubernetes/jib/JibServiceUtil.java
fabric8:push with Jib Mode fails to push image tags with strings consisting "-SNAPSHOT".
=> Fix: Jib push fails to push configured tag

CHANGELOG.md, core/src/main/java/io/fabric8/maven/core/service/kubernetes/jib/JibAssemblyManager.java
in the jib mode, if you use 'tar', 'zip' or 'tgz' mode, the configured files in the assembly config are not 'assembled' inside the built container image. Only 'dir' mode works.
=> Fix: JIB Assembly config doesn't work with any Archive mode

CHANGELOG.md, README.md, enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ConfigMapEnricher.java
This also seems to be a sideeffect of sundrio configuration change, A user
emailed about this problem.
To reproduce you can simply run fabric8:resource on one of these samples:
https://github.com/r0haaaan/eclipse-jkube-sample-with-resource-fragments
I checked again and I think this was the last place where annotations were being accessed unsafely.  At other places it seems we're just appending newly created annotation depending upon enricher
```
~/work/repos/fabric8-maven-plugin : $ git grep -in "getAnnotations()" | grep "Enricher.java"
enricher/deprecated/src/main/java/io/fabric8/maven/enricher/deprecated/CdEnricher.java:95:    public Map<String, String> getAnnotations() {
enricher/deprecated/src/main/java/io/fabric8/maven/enricher/deprecated/CdEnricher.java:127: …
```
=> Fix NullPointerException in ConfigMapEnricher

CHANGELOG.md, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/PushMojo.java
fabric8:push goal seems to be failing due to no docker deamon
initialization being done. The cause seemed to be function isDockerAccessRequired()
which was ignoring the fact that docker access is also used in openshift mode. If we
don't specify any mode explicitly it is set to RuntimeMode.auto.
I think we should disable docker access check only when JIB=true
=> Fix fabric8:push goal in auto mode

parent/pom.xml
some tests were breaking after updating `fabric8/java-centos-openjdk` to latest versions:
https://github.com/manusa/fmp-integration-tests/runs/606943813?check_suite_focus=true
=> Revert to 1.5 version for Fabric8 Images

doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/PushMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DeployMojo.java
Based upon https://github.com/fabric8io/fabric8-maven-plugin/pull/1471#issuecomment-645198834
=> Skip properties should have fabric8 prefix rather than docker

core/src/main/java/io/fabric8/maven/core/util/Fabric8MavenPluginDeprecationUtil.java, core/src/test/java/io/fabric8/maven/core/util/Fabric8MavenPluginDeprecationUtilTest.java, doc/src/main/asciidoc/inc/_introduction.adoc, doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc, plugin/src/main/java/io/fabric8/maven/plugin/mojo/AbstractFabric8Mojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java, plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/PushMojo.java
Related to https://github.com/eclipse/jkube/issues/1426
Add warning log message to print deprecation message and instruct users
to migrate to Eclipse JKube
Signed-off-by: Rohan Kumar <rohaan@redhat.com>
=> feat : Add Fabric8 Maven Plugin deprecation log message before & after goal executions
